### ISSUE TITLE
UI problem going up tree from /secret to /

### ISSUE THREAD

**Issue by dswhite42** [Caiyeon/goldfish#108]
Steps to reproduce (with a standard vault and goldfish setup):

Assume we have a layout of:
    /secret/
        /secret/mystuff/
            /secret/mystuff/bankinfo
            /secret/mystuff/secretcode
        /secret/otherstuff/

1. Login and click the "Secrets" link on the left.  In the main frame, the top section will show "secret/" while the bottom section will show a number of child subpaths ("mystuff/", "otherstuff/")
2. Click a subpath (e.g. "mystuff/").  Top section now shows "secret/mystuff/" and the bottom section shows a new section of subpaths ("bankinfo", "secretcode")
3. Click the green "up arrow" in the top section.  Top section now shows "secret/" once again and "mystuff/" and "otherstuff/" in the bottom section.
4. Click the green "up arrow" in the top section again.  An "Error: 500 - Invalid vault response" error box pops up.  Top section now shows "/".  **However**, the bottom section still shows "mystuff/" and "otherstuff/".
5. Click "mystuff/" in the bottom section.  Another "Error: 500 - Invalid vault response" error box pops up.

Workaround to get out this situation:

- Manually change the top section back to "secret/"
- Or click away to another section of Goldfish (e.g. a tool or admin policy), the click "Secrets" in the left navbar again.

But probably Goldfish should not show the "secret/" subpaths below an invalid path like "/".  This error also occurs if you manually try to enter a secret location in the top section that is wrong (e.g. secret/some/bad/path/here) - the error box appears, but the bottom section of subpaths is not cleared out and still shows the subpaths of the last valid path.

**Comment by Caiyeon** [comment]
This bug actually resulted from me not properly cleaning up a deprecated function.
The resulting problem is two-fold:
1. Moving up when already at a mount's top-level should be disallowed
2. Upon encountering an error (e.g. if vault permissions are denied), the entire table data should be cleared out. This will ensure that the user knows he is unable to reach this path, and will need to re-enter the path manually or refresh the page to be taken back to default path.

Will be fixed soon.

**Comment by dswhite42** [comment]
Great - thank you.

**Comment by Caiyeon** [comment]
Fixed. Will be included in the next release.
