### ISSUE TITLE
Secrets containing ampersands are not properly created

### ISSUE THREAD

**Issue by dswhite42** [Caiyeon/goldfish#109]
I tried creating a secret called **secret/This&That** , but the resulting secret was named **secret/This** .  Perhaps special characters like (&) are not being escaped?

**Comment by Caiyeon** [comment]
Ah, silly me. The backend API takes the path as a query parameter, which means & needs to be escaped.

But the proper fix is to actually turn this to a form param or json body.

**Comment by Caiyeon** [comment]
I take that back. The read request would have to be used without a body. I simply url encoded the query parameter. Reopen this if you see characters that aren't escaped properly.

Fun fact: vault secret paths can contain unicode
