### ISSUE TITLE
Move focus to "Key" (instead of "Value") when adding multiple key/value pairs

### ISSUE THREAD

**Issue by dswhite42** [Caiyeon/goldfish#111]
This is more a "feature request" than an issue, but it'd be nice, when adding multiple keys and values, to have the active field be the "Key" field as new key/value pairs are added for a secret.

That is, when adding a new secret, you can type in a "Key", hit <TAB>, type in the "Value", then hit <ENTER> to save the pair.  A new key/value pair of lines appears below that so you can enter more values... but the focus is on the "Value" field.  It would be better to put the focus on the new "Key" field instead.

Thanks!

**Comment by Caiyeon** [comment]
Thanks for the input (ha! input field... get it?)

Autofocus added to appropriate fields when creating a new secret or creating new key/value pairs. Focus is shifted to the key field upon entering a key/value pair.

Should be in v0.4.2
