### ISSUE TITLE
Vue does not change TableHeaders on Add Secret K/V

### ISSUE THREAD

**Issue by Techcadia** [Caiyeon/goldfish#114]
When adding a Secret you type the then and press enter when it drop you into add the key values the TableHeaders still have 
https://github.com/Caiyeon/goldfish/blob/v0.5.0-rc1/frontend/client/views/secrets/index.vue#L327

Not
https://github.com/Caiyeon/goldfish/blob/v0.5.0-rc1/frontend/client/views/secrets/index.vue#L336

Should be simple I just don't understand vue enough to fix.

**Comment by Caiyeon** [comment]
I see what you mean. Yes this is a minor cosmetic bug, and it'll be fixed in v0.5.0. Thanks for the report!
