### ISSUE TITLE
404s when trying to look at generic mounts which are not directly off the root

### ISSUE THREAD

**Issue by elliottsam** [Caiyeon/goldfish#115]
When I try and look at generic mounts that are not mounted off the root, I am unable to view the options, for them. Just receive 404s through the UI
e.g.
Works - `secret/`
Fails - `nested/mount/`

**Comment by Caiyeon** [comment]
Interesting. Out of curiosity, what is the use case of nested mounts? I did not know this was possible.

**Comment by elliottsam** [comment]
So we have mounts for different teams and then use the first part of the mount for environment type
i.e.
dev/team1
prod/team1

It just makes things clearer when using the vault cli tool to see what generic mounts are configured and also for some of our internal tooling.
