### ISSUE TITLE
Only Secret mount gets shown

### ISSUE THREAD

**Issue by elliottsam** [Caiyeon/goldfish#116]
When looking at secrets, it is only the secret mount that is shown to browse thorough. I am able to type in the path to other mounts and then they are visible, but it would be good if the app could display all generic mounts to begin with

**Comment by Caiyeon** [comment]
The default secret path can be changed by writing into the config path in vault where goldfish will reload its settings from automatically. https://github.com/Caiyeon/goldfish/wiki/Configuration#basic-required

There used to be a way to list mounts in the secrets page, but it has been deprecated. 

For most users that are using an UI, they would likely have list access on at least one of the generic mounts, which should be the default entrypoint. In the case where a user wants to read another mount, they should know the mount endpoint already, or go to mounts page to find the right one.

**Comment by elliottsam** [comment]
Okay, this is a bit of a problem for us at developers in different teams may not know the paths especially if new to the project.

What was the reason for removing this functionality, did it cause other issues?

**Comment by Caiyeon** [comment]
It was removed because it was out of place, and the mounts page made it redudant. Is a visit to the mounts page until they remember the path too difficult? Or is there simply no particular secret mount that most users are allowed to read?

**Comment by dmlemos** [comment]
I realised the generic mounts view tree is crucial as different teams have their own. Specifying the path every time is counter-intuitive.
It is a shame as I really like the interface, but cannot use it because of this reason.

I am sure if I am going off topic, but I don't know what is the builtins. Could you perhaps explain please?
