### ISSUE TITLE
No more Windows binaries?

### ISSUE THREAD

**Issue by johnjelinek** [Caiyeon/goldfish#117]
In `0.5.0` I don't see a windows binary. Is Windows no longer supported?

**Comment by Caiyeon** [comment]
Apologies, I didn't realize anyone actually used the windows binary.

I should note that it's a lot harder (if not impossible) to lock down the memory on windows, so be careful when deploying goldfish (same with vault itself)

Let me know if you actually use the windows binary and I will compile it from that version's tag.

**Comment by johnjelinek** [comment]
I see Windows binaries now, thanks!

**Comment by fenneh** [comment]
FYI - I'm also using the windows binary.
