### ISSUE TITLE
Redraw screen when attempting to go above top-level of mount

### ISSUE THREAD

**Issue by dswhite42** [Caiyeon/goldfish#121]
Thanks for fixing #108 !  Just one further suggestion related to those GUI issues, which can be seen with this process:

- Login as a relatively unprivileged user.  
- Click "Secrets" on the left navbar
- In the right frame, the upper portion shows the path (secret/) and the lower portion shows some secrets.
- Click the "goldfish" secret in the lower portion.  A "Vault: permission denied" message appears.  Also, all secrets listed in the lower pane disappear, but the top portion still shows that our location is "secret/"
- Click the green "up arrow" on the top section.  Message appears "Already at top level of mount", but the secrets that should be visible at this level are not displayed below.

Again there are several workarounds (e.g. click a different section in the left navbar like "Login", then click "Secrets" again to reset the display) but perhaps it would be better if the lower portion of the screen was redrawn to coincide with the current location every time a secret is clicked, even if that click only generated an error message?

Thanks!

**Comment by Caiyeon** [comment]
Indeed, if the current path isn't changed, the table data shouldn't be wiped. As well, it seems like it's not obvious enough to the end user that the secrets path bar can be manually re-confirmed by pressing enter to solve this problem. Perhaps I'll put a button somewhere in the bar as well

**Comment by Caiyeon** [comment]
Fixed in https://github.com/Caiyeon/goldfish/commit/c03ad48b7e80a397118a735c0a58daa6fef23072
