### ISSUE TITLE
LDAP User and Group Management

### ISSUE THREAD

**Issue by lucymhdavies** [Caiyeon/goldfish#122]
Vault (and Goldfish) supports LDAP auth.

It would be nice to be able to manage that from within Goldfish. i.e. mapping users and groups to policies.

Would be even better if we could use the same sort of request feature that Goldfish already has for policies

**Comment by Caiyeon** [comment]
I would love to support LDAP (listing and viewing, at the very minimum). Problem is, I haven't found a graceful way to make this testable. Ideally, launching goldfish in dev mode should also launch a local LDAP server and initialize some data.

If you/someone else wants to tackle this, a pull request would be welcomed.

As for the request feature, it's very specific to policies at the moment. But generalizing the system is in my (somewhat distant) scope.

**Comment by Caiyeon** [comment]
Listing and viewing LDAP groups/users added in https://github.com/Caiyeon/goldfish/commit/975e1be27d9b6cd8ad82392f3f46b2b242b013ca

Requests system should be tracked in a separate issue, when I can find the time to fully map out the specifications

**Comment by lucymhdavies** [comment]
Cool. Thanks.

This alone should be useful. :)
