### ISSUE TITLE
"Error: Goldfish could not use transit key"

### ISSUE THREAD

**Issue by dswhite42** [Caiyeon/goldfish#124]
Hi, Tony.  I upgraded from Goldfish 0.4.1 to 0.5.0 last week, and everything was working fine.  This morning when I go to login, I'm getting this:

Error: 500
Goldfish could not use transit key 

Is there an expiration problem or key-refresh issue that's not happening?  

Thanks for all your work.

**Comment by Caiyeon** [comment]
Goldfish will proactively renew its own token every hour, so as long as it has the `default` policy, it will continue to live until `max_ttl` (~720h) if it is set, or forever, if the goldfish approle is set to be periodic.

That leaves two possibilities:
1. Goldfish token accessor was revoked by someone else
2. Goldfish approle or policy was changed/removed

Redeploying goldfish is likely faster than a debug session, as I am busy for the next few days. If your deployment script is setup correctly, it should take no more than a few minutes. This should be even easier as of 0.5.0 - user session persists through redeployments.

I will keep this ticket open to remind myself to change the error message to be more finegrained so it won't cause ambiguity in the future. If you find the root cause somehow, let me know :)

**Comment by dswhite42** [comment]
Hmm.  I did try to follow the redeployment steps for 0.5.0, and assumed any new policy directives would overwrite old ones.  Here's what the goldfish approle looks like:

    Key                     Value
    ---                     -----
    bind_secret_id          true
    bound_cidr_list   
    period                  86400
    policies                [default goldfish]
    secret_id_num_uses      1
    secret_id_ttl           300
    token_max_ttl           2592000
    token_num_uses          0
    token_ttl               1728000

and in JSON from the API:

    {
      "request_id": "76731429-92b4-91d4-1f92-a58390adde32",
      "lease_id": "",
      "renewable": false,
      "lease_duration": 0,
      "data": {
        "bind_secret_id": true,
        "bound_cidr_list": "",
        "period": 86400,
        "policies": [
          "default",
          "goldfish"
        ],
        "secret_id_num_uses": 1,
        "secret_id_ttl": 300,
        "token_max_ttl": 2592000,
        "token_num_uses": 0,
        "token_ttl": 1728000
      },
      "wrap_info": null,
      "warnings": null,
      "auth": null
    }

If that's still not useful, I can go ahead and try to redeploy.  Do I need to add other commands before I follow the deployment instructions, to clear out existing data?  Or do the new policies indeed clear out the old ones?

**Comment by Caiyeon** [comment]
Writing to policy or approle will overwrite the previous copy. The only thing I see in your approle is that period, ttl, and max_ttl tend to conflict, so i personally just set period and not ttl/max_ttl. But this should not cause breakage.

It's up to you to redeploy just step 3 or steps 1 to 3. I'm not seeing any obvious problems either way.

This reminds me, I should get goldfish to report its token accessor in the UI so that it can be revoked/tracked if needed be.

**Comment by dswhite42** [comment]
Ok, I did a full redeploy, even deleting the old policy and approle.  (without deleting it, the old **token_max_ttl**  and **token_ttl** values are not cleared out when the new policy is inserted).  It's back up now, and I'll let you know if anything weird happens in a few days.

    > vault policy-delete goldfish                             
    Policy 'goldfish' deleted.

    > curl -X DELETE -H "X-Vault-Token: $VAULT_ROOT_TOKEN" $VAULT_ADDR/v1/auth/approle/role/goldfish

    > vault read auth/approle/role/goldfish
    No value found at auth/approle/role/goldfish

    > vault policy-write goldfish vagrant/policies/goldfish.hcl
    Policy 'goldfish' written.

    > vault write auth/approle/role/goldfish role_name=goldfish policies=default,goldfish secret_id_num_uses=1 secret_id_ttl=5m period=24h
    Success! Data written to: auth/approle/role/goldfish

    > vault write auth/approle/role/goldfish/role-id role_id=goldfish
    Success! Data written to: auth/approle/role/goldfish/role-id

    > vault write -f transit/keys/goldfish
    Success! Data written to: transit/keys/goldfish

    > vault write secret/goldfish DefaultSecretPath="secret/" TransitBackend="transit" UserTransitKey="usertransit" ServerTransitKey="goldfish" BulletinPath="secret/bulletins/"
    Success! Data written to: secret/goldfish

    > export WRAP_TOKEN=`vAULT write -f -wrap-ttl=20m -format=json auth/approle/role/goldfish/secret-id | jq -r .wrap_info.token`

    > nohup goldfish -config=/apps/vault/goldfish/goldfish_config.hcl -token=$WRAP_TOKEN >> /apps/vault/goldfish/logs/goldfish.log 2>&1 &

    > vault read auth/approle/role/goldfish
    Key                     Value
    ---                     -----
    bind_secret_id          true
    bound_cidr_list
    period                  86400
    policies                [default goldfish]
    secret_id_num_uses      1
    secret_id_ttl           300
    token_max_ttl           0
    token_num_uses          0
    token_ttl               0

**Comment by dswhite42** [comment]
I'm afraid the error has resurfaced again, even after the full redeploy I described above.  I go to the Goldfish page and try to login, and get "Error: 500 - Goldfish could not use transit key "

The last goldfish log entry:

    {"time":"2017-07-19T16:41:26.569413406-05:00","id":"",
    "remote_ip":"2001:420:20b0:1:5855:3c22:3b45:98b3",
    "host":"myhost.example.com:8443","method":"POST","uri":"/api/login",
    "status":500, "latency":49407697,"latency_human":"49.407697ms",
    "bytes_in":53,"bytes_out":46}

The last vault log entry:

    {"time":"2017-07-19T16:41:03.22298353-05:00","id":"",
    "remote_ip":"2001:420:20b0:1:5855:3c22:3b45:98b3",
    "host":"myhost.example.com:8443","method":"POST","uri":"/api/login",
    "status":500, "latency":50586085,"latency_human":"50.586085ms",
    "bytes_in":53,"bytes_out":46}

Goldfish configuration:


    $ vault read auth/approle/role/goldfish

    Key                     Value
    ---                     -----
    bind_secret_id          true
    bound_cidr_list
    period                  86400
    policies                [default goldfish]
    secret_id_num_uses      1
    secret_id_ttl           300
    token_max_ttl           0
    token_num_uses          0
    token_ttl               0

    $ vault read transit/keys/goldfish
    
    Key                     Value
    ---                     -----
    deletion_allowed        false
    derived                 false
    exportable              false
    keys                    map[1:1498012526]
    latest_version          1
    min_decryption_version  1
    name                    goldfish
    supports_decryption     true
    supports_derivation     true
    supports_encryption     true 
    supports_signing        false
    type                    aes256-gcm96

    $ vault read secret/goldfish

    Key                     Value
    ---                     -----
    refresh_interval        768h0m0s
    BulletinPath            secret/bulletins/
    DefaultSecretPath       secret/
    GithubAccessToken
    GithubCurrentCommit
    GithubPoliciesPath
    GithubRepo     
    GithubRepoOwner
    GithubTargetBranch
    LastUpdated             Tue Jul 18 12:59:04 CDT 2017
    ServerTransitKey        goldfish
    SlackChannel   
    SlackWebhook   
    TransitBackend          transit
    UserTransitKey          usertransit

**Comment by Caiyeon** [comment]
Do you have the accessor of goldfish's token by chance?

**Comment by dswhite42** [comment]
I'm sorry, I don't know what that is.  How would I find it?  Or at what point in my redeploy would it be displayed?

**Comment by Caiyeon** [comment]
When launching goldfish it should display the server's token accessor in stdout.
But nevermind that, you can actually force goldfish to bypass transit by going into your chrome dev console and changing your localstorage

This value should be prefixed with `vault:v1`. You can force bypass transit by giving it your own raw token.

![image](https://user-images.githubusercontent.com/6126493/28393303-e65e4864-6c9a-11e7-96c0-bd36de2f4b84.png)


Most functionality will remain. Could you do this, and go to Users page, and search for tokens with `goldfish` policy?

Because the approle is set to periodic, the token you are looking for must have a ttl of under 86400. If there is no such token, then the server's token has been revoked (or timed out).

This reminds me, does your default policy allow for token self renewal?
```
# Allow tokens to renew themselves
path "auth/token/renew-self" {
    capabilities = ["update"]
}
```

**Comment by dswhite42** [comment]
I had to restart Goldfish (with a new wrap token) in order to get it working, but I can at least see now that the accessor token of the current version has a TTL of 84344 (because it just started).  However, I was able to see the token ID of the previous accessor from the Goldfish logs.  That token did not appear anywhere in the list of Users->Tokens on Goldfish.

Regarding this:

    # Allow tokens to renew themselves
    path "auth/token/renew-self" {
        capabilities = ["update"]
    }

where should this configuration be added?  I do not see it either as part of the goldfish_config.hcl or my vault server_config.hcl.  Should I add it to one of them?  

And is there a way to check with the currently running vault whether this is active or not?

**Comment by Caiyeon** [comment]
It's safe to assume either the token timed out or was revoked.

That policy snippet should be in your `default` policy.

**Comment by dswhite42** [comment]
Ah, I see.

    $ vault read sys/policy/default

    ...
    # Allow tokens to renew themselves
    path "auth/token/renew-self" {
        capabilities = ["update"]
    }

Since that is set, what else could be causing the token to time out or be revoked?  (it's certainly not being done manually by anyone).  I do see a few entries like this in vault's logfile:

    vault.log:2017/07/17 15:43:51.183523 [INFO ] expire: revoked lease: lease_id=auth/approle/role/goldfish/secret-id/b4fa4e05059a56ecb6b01073493316b022daff61
    vault.log:2017/07/18 13:14:18.431444 [INFO ] expire: revoked lease: lease_id=auth/approle/role/goldfish/secret-id/9cd0b84f0ec415a4e69f94aff636caaffb1bc5e4
    vault.log:2017/07/18 13:14:28.847402 [INFO ] expire: revoked lease: lease_id=auth/approle/role/goldfish/secret-id/5d43e8d3c37a65b8d69780abcfb98ce7bd0c68b2
    vault.log:2017/07/18 13:16:54.322051 [INFO ] expire: revoked lease: lease_id=auth/approle/role/goldfish/secret-id/4fcb8a6e89a5ce9b18f5cac16bd031f12f89ae9b
    vault.log:2017/07/18 13:18:30.084050 [INFO ] expire: revoked lease: lease_id=auth/approle/role/goldfish/secret-id/7ce265b9c0d272f5185cd5049fcb208123974c87

but I don't know if they are relevant.

**Comment by Caiyeon** [comment]
That should not be relevant. I assume you've created wrapping tokens and they timed out after not being used.

Goldfish tries to renew itself every hour, and if any errors occur, it will print out `[ERROR]: {error msg}` in stdout. I assume you saw nothing of this sort?

Your best bet may be to parse through vault's audit log to see goldfish's request to renew its own token. This should happen approximately every hour after it is deployed. Vault's audit log will show what vault responded with (whether the renewal was a success or not)

**Comment by Caiyeon** [comment]
Did goldfish work 24 hours after each deployment? Because at least one renewal would have had to been successful for goldfish to be still useable after 24 hours.

Here's what the audit entries should look like if the renewal went well:

Request:
```json
{
    "time": "2017-07-20T01:39:56Z",
    "type": "request",
    "auth": {
        "client_token": "hmac-sha256:e8cd7a215d1153c3108cc58fbc2b328e171b45ce7175ba4305ddd570bda008d5",
        "accessor": "hmac-sha256:b0d4d3d78d91dd7911882077ebd1a1781b30d88c889da4b5e04e7d376da91b43",
        "display_name": "approle",
        "policies": [
            "default",
            "goldfish"
        ],
        "metadata": {}
    },
    "request": {
        "id": "2199310c-e267-2b08-54c8-f78c37a71451",
        "operation": "update",
        "client_token": "hmac-sha256:e8cd7a215d1153c3108cc58fbc2b328e171b45ce7175ba4305ddd570bda008d5",
        "client_token_accessor": "hmac-sha256:b0d4d3d78d91dd7911882077ebd1a1781b30d88c889da4b5e04e7d376da91b43",
        "path": "auth/token/renew-self",
        "data": {
            "increment": "hmac-sha256:c5e255747338c5e49992d579c32af6bc2438da6f646f9c062cc370202518bc26"
        },
        "remote_address": "127.0.0.1",
        "wrap_ttl": 0,
        "headers": {}
    },
    "error": ""
}
```
Response:
```json
{
    "time": "2017-07-20T01:39:56Z",
    "type": "response",
    "auth": {
        "client_token": "hmac-sha256:e8cd7a215d1153c3108cc58fbc2b328e171b45ce7175ba4305ddd570bda008d5",
        "accessor": "hmac-sha256:b0d4d3d78d91dd7911882077ebd1a1781b30d88c889da4b5e04e7d376da91b43",
        "display_name": "approle",
        "policies": [
            "default",
            "goldfish"
        ],
        "metadata": {}
    },
    "request": {
        "id": "2199310c-e267-2b08-54c8-f78c37a71451",
        "operation": "update",
        "client_token": "hmac-sha256:e8cd7a215d1153c3108cc58fbc2b328e171b45ce7175ba4305ddd570bda008d5",
        "client_token_accessor": "hmac-sha256:b0d4d3d78d91dd7911882077ebd1a1781b30d88c889da4b5e04e7d376da91b43",
        "path": "auth/token/renew-self",
        "data": {
            "increment": "hmac-sha256:c5e255747338c5e49992d579c32af6bc2438da6f646f9c062cc370202518bc26"
        },
        "remote_address": "127.0.0.1",
        "wrap_ttl": 0,
        "headers": {}
    },
    "response": {
        "auth": {
            "client_token": "hmac-sha256:e8cd7a215d1153c3108cc58fbc2b328e171b45ce7175ba4305ddd570bda008d5",
            "accessor": "hmac-sha256:b0d4d3d78d91dd7911882077ebd1a1781b30d88c889da4b5e04e7d376da91b43",
            "display_name": "approle",
            "policies": [
                "default",
                "goldfish"
            ],
            "metadata": {}
        }
    },
    "error": ""
}
```

**Comment by Caiyeon** [comment]
Hang on, I think I found the bug. This is silly of me. I should have caught this on the demo, but I neglected to update the demo vault's approle to periodic.

You'll see a fix in 0.5.1 soon.

**Comment by Caiyeon** [comment]
Fixed in https://github.com/Caiyeon/goldfish/commit/e42ba32da96d7f8cdd001ace81af6bd34e2ebc61
Release: https://github.com/Caiyeon/goldfish/releases/tag/v0.5.1

Cheers, and thanks for the catch!

**Comment by Caiyeon** [comment]
For the curious, this bug resulted from the error channel being not properly initialized. This means that the first renewal will succeed, but the result will be "stuck" in the channel pipe, and therefore the goroutine that is responsible for renewing cannot proceed. This means that goldfish can be alive for a max of 2 * token's TTL, which is approximately 2 days given the new approle settings.

**Comment by TolikT** [comment]
Hello @Caiyeon,
I have the same issue. Could you help?

Environment:
```
Goldfish version - 0.8.0
Vault version - 0.9.0
Both are dockerized, used your configuration.
```
Vault works ok, but goldfish can't perform authentication. The full mesage is:

```
Error: 500
Goldfish could not use transit key: Error making API request. URL: PUT http://vault:8200/v1/transit/encrypt/goldfish Code: 403. Errors: * permission denied
```

Logs:
```
2018/01/04 10:07:48.160176 [INFO ] expiration: revoked lease: lease_id=auth/token/create-orphan/ecced90b5767d57c8a1bfc76833b3ad2b3beb32d
2018/01/24 15:20:33.346247 [INFO ] expiration: revoked lease: lease_id=auth/ldap/login/user/847b8c3a10c489515a0d96b0aaf2cced8c631199
2018/01/25 11:21:33.805880 [INFO ] expiration: revoked lease: lease_id=auth/ldap/login/user/fd5fbdba78eabdae49f8d01c5a38324383767f6a
2018/01/26 13:10:34.743572 [INFO ] expiration: revoked lease: lease_id=auth/approle/login/dae5df30f56a903e640b2ab302bf58067c047ce2
```

**Comment by Caiyeon** [comment]
@TolikT double check that goldfish's policy allows it to use the transit key you configured. Alternatively, you can remove the `ServerTransitKey` from the runtime configurations. If neither of these options work, please open a new issue. This one should be frozen due to age.
