### ISSUE TITLE
Searching/Filtering Secrets

### ISSUE THREAD

**Issue by fia5000** [Caiyeon/goldfish#126]
If we can have searching/filtering for policy and tokens.. why not have it for secret listings as well?

**Comment by Caiyeon** [comment]
Are you suggesting traversing secrets as a tree? Secrets are inherently structured differently from policies and tokens. A user may be able to read `secret/foo/bar` but may not be able to list `secret/foo`, and therefore a traversal would not work optimally.

Ideally, a vault instance should be structured such that no deep traversal is necessary to find a specific key.
