### ISSUE TITLE
Can't buy you coffee  :-)

### ISSUE THREAD

**Issue by dswhite42** [Caiyeon/goldfish#130]
1. Go to https://ko-fi.com/caiyeon
2. Click "Support Caiyeon"
3. Get a "ERR_CONNECTION_CLOSED (www.paypal.com unexpectedly closed the connection)" message.  It happened in 3 different browsers.

I tried!

**Comment by Caiyeon** [comment]
Looks like you tried again recently and it went through! Thanks for the donation and support :)

**Comment by dswhite42** [comment]
Yep, it worked that time.  Thanks again!  :coffee:
