### ISSUE TITLE
Dependencies => "Check all approles" does not seem to work

### ISSUE THREAD

**Issue by andrewsav-datacom** [Caiyeon/goldfish#132]
I have an app role "a" with a policy "b". I go to the Dependencies tab and select "Policy" from the drop down. I Press "List policies". I choose policy "b" from the list and I press "Confirm". I press "Check all approles" then. I'm getting "Error: 404. Not found". I expect to see the "a" app role.

Is this working as expected?

**Comment by Caiyeon** [comment]
That is not expected behaviour, and will be fixed soon

**Comment by Caiyeon** [comment]
Fixed in tag `v0.5.1` 5494004
Fixed in branch `master` 46f7018
Binaries rebuilt and reuploaded https://github.com/Caiyeon/goldfish/releases/tag/v0.5.1
