### ISSUE TITLE
Layout issues when browser window is not full screen

### ISSUE THREAD

**Issue by andrewsav-datacom** [Caiyeon/goldfish#133]
When the browser window (chrome) is resized, the layout gets skewed as on this picture:

![2017-07-25_13-08-57](https://user-images.githubusercontent.com/27190911/28551222-d12fd814-713a-11e7-8b18-d55917e3fa81.png)

**Comment by Caiyeon** [comment]
Resizing of tiles is dependent on [bulma](bulma.io), and for the foreseeable future I won't be dedicating time to resolve sizing issues on non-desktop DPIs. The minimum width is approximately 1000px (the average 1080p monitor will have 1920px width, so this is a little more than half)
