### ISSUE TITLE
List the Permissions Required to Create Wrapped Token

### ISSUE THREAD

**Issue by noahjohnhay** [Caiyeon/goldfish#135]
https://github.com/Caiyeon/goldfish/blob/master/docker/entrypoint.sh#L30
https://github.com/Caiyeon/goldfish/wiki/Production-Deployment#2-generating-a-secretid-from-approle-needed-for-every-redeployment

To create the wrapped token the examples above assume you are authenticated using the root token. I have written a auto scaling deployment which consists of using IAM auth backend to requests a token as I dont want a token stored in the user data. I would like to use this to be able to requests the wrapped token for goldfish. I don't want to give the IAM auth root level permissions, if you could elaborate on which permissions are required to perform the above actions it would be greatly appreciated.

An other option I have considered is giving the IAM auth the permissions goldfish requires and then wrapping said token and providing it in startup, but am also having issues wrapping the token. Is providing a wrapped token required or is there a way I can wrap the token before providing it to goldfish?

**Comment by Caiyeon** [comment]
I would not recommend using a root token to generate this wrapping token. All you need is write access to auth/approle/role/goldfish/secret-id  you can see here for more details https://www.vaultproject.io/docs/auth/approle.html

Goldfish strictly uses the pull method of approle for security reasons, so you cannot wrap a regular token and give that to goldfish
