### ISSUE TITLE
Delete confirmation dialogue

### ISSUE THREAD

**Issue by Ubeek** [Caiyeon/goldfish#137]
Currently when deleting a secret, no confirmation dialogue is presented and the secret is immediately removed.

Ideally this action should present a confirmation dialogue allowing the user to review they have chosen the correct secret, as reversal of this action is not possible.

**Comment by Caiyeon** [comment]
Agreed. But at the moment, modals are just too much time to construct. What if the delete button, upon clicking, turned into a confirmation button that required another click? Similar to the reject button on requests.

**Comment by Ubeek** [comment]
I think that's a very reasonable middle ground. Any extra step at this point adds a lot of "safety" to that process.

**Comment by Caiyeon** [comment]
Added in e011a1c

![image](https://user-images.githubusercontent.com/6126493/28860842-0c04fc34-7713-11e7-87a6-479684fb8178.png)
