### ISSUE TITLE
Permission denied when approving a change request

### ISSUE THREAD

**Issue by adampointer** [Caiyeon/goldfish#139]
Hi,

The goldfish.hcl file in vagrant/policies needs updating for change approval to work.

```
path "sys/wrapping/wrap" {
  capabilities = ["update"]
}

path "sys/wrapping/unwrap" {
  capabilities = ["update"]
}

```

Not sure if the unwrap is required but we chucked it in anyway and it solved it.

**Comment by Caiyeon** [comment]
Wrapping, unwrapping, and cubbyhole access are required for requests.
This should be all included in the default policy, which is in the deployment setup.

You can also look at the demo policies: https://vault-ui.io/#/policies
I can assure you requests work on the demo with just policies `goldfish` and `default`
