### ISSUE TITLE
Disable request change

### ISSUE THREAD

**Issue by argais** [Caiyeon/goldfish#144]
Is there any way I can disable the need to use unseal tokens for this?

While the idea is neat, and might be great for whoever is ok with it, I'd like to just have admin users with permissions to actually create/change policies to be able to authorize it themselves, or even skip the need to do so completely.

**Comment by Caiyeon** [comment]
A token that can modify policies is essentially a pseudo root token. See #131 

If you wish to provide this ability to individuals, you might as well provide them with sufficient unseal keys. As far as I know, this is only minorly more privileged (e.g. ability to seal & unseal). Then they can roll policy changes individually.

It should be noted that one of goldfish's core goals is to make quorum decisions easier - not to remove it altogether.
