### ISSUE TITLE
Live demo unreachable

### ISSUE THREAD

**Issue by achaussier** [Caiyeon/goldfish#148]
Hello,

It seems the live demo is unreachable:

```
 / > tmp > 09:33:47 > curl -SIv --connect-timeout 30 https://vault-ui.io/
*   Trying 67.205.184.214...
* Connected to vault-ui.io (67.205.184.214) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 692 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* Operation timed out after 0 milliseconds with 0 out of 0 bytes received
* Closing connection 0
curl: (28) Operation timed out after 0 milliseconds with 0 out of 0 bytes received
 / > tmp > 09:34:23 > 28 > 
```

**Comment by Caiyeon** [comment]
Not sure what your network configuration is like, but the demo is fully up

http://downforeveryoneorjustme.com/vault-ui.io

**Comment by Caiyeon** [comment]
I should mention that there is a problem with the demo's vault instance. Something is causing vault to not respond to requests, but this has nothing to do with goldfish. I'll look into it when I have the time. At the moment though, the website should load, it just won't serve vault requests

**Comment by achaussier** [comment]
Hello, 
After a Chromium restart, I can see the website.

Thanks
