### ISSUE TITLE
Auth Backend: LDAP

### ISSUE THREAD

**Issue by freman** [Caiyeon/goldfish#15]
Is this dependant on the SAML-LDAP integration?

If not, it's sorely missed :D

**Comment by Caiyeon** [comment]
This would only take minutes to code, but I've been pushing it back because I would need to set up LDAP myself to test.

Would you be able to test this feature?

**Comment by Caiyeon** [comment]
@freman This commit should allow LDAP logins: https://github.com/Caiyeon/goldfish/commit/726703672f19f368188c445fe3001a09951b4e99

Frontend behaviour would be similar to how a user pass login looks like. That is, the user logging in should be notified of the client token generated, and the client token should work on a token login thereafter. (Try it on the demo to see what I mean) 

Let me know if this works/doesn't work

**Comment by freman** [comment]
Thanks for jumping on that so quickly

URL: PUT https://vault.service.dc1.consul:8200/v1/auth/ldap/loginmyname
Code: 400. Errors:

Seems to be missing a slash, if I log in with /myname then it works fine :D

**Comment by Caiyeon** [comment]
Great. I'll add the slash in. If you're certain that once the slash is added, everything works as expected, you can feel free to close this :)

**Comment by freman** [comment]
Looks good to me, sorry it took so long to get back to you
