### ISSUE TITLE
Feature: Add option to get unwrapped token from environment or file

### ISSUE THREAD

**Issue by justenwalker** [Caiyeon/goldfish#150]
It would be great if Goldfish were able to get it's vault token from either a file or environment variable; in addition to the current way of retrieving it via a wrapped token or AppRole. This would enable the project to be hosted on Nomad using the built-in vault integration, which automatically generates a vault token and passes it to the container through the VAULT_TOKEN environment variable or a secret file containing the token.

**Comment by Caiyeon** [comment]
You can pass in the wrapping token via 'token' cmd line arg. Is this sufficient?

**Comment by justenwalker** [comment]
No, the nomad token is not wrapped, so unwrapping fails.

**Comment by Caiyeon** [comment]
But if goldfish could use an unwrapped secret ID in cmd line arg then it would work for nomad?

**Comment by justenwalker** [comment]
Yeah, but passing an unwrapped token as an arg basically advertises it;
which is insecure. Getting it from a secret file is probably better. I can
submit a patch if that helps.

**Comment by Caiyeon** [comment]
Are you intending to pass in a secret_id from approle or a raw token? The former should not be compromised since the service has to login with a secret_id to fetch its own client token

**Comment by justenwalker** [comment]
Raw token. Nomad does not support the former.

**Comment by Caiyeon** [comment]
Really? Nomad doesn't support approle...? That's silly. I've been against the idea of handing a raw token to goldfish, because it may lead to users deploying it with a raw taken from a vault operator, which would of course compromise the unseal tokens in the request system.

I'll see if I can find a good compromise by having a key inside `config.hcl` with a name that has enough warnings to indicate the dangers

**Comment by justenwalker** [comment]
I tried before. See: https://github.com/hashicorp/nomad/issues/2171

**Comment by justenwalker** [comment]
While I admire the purity argument; the realities are always at least slightly uglier.  If I have to rely on my custom patch then so be it - but I'd really like to be able to use Goldfish in my environment without hacking it...

**Comment by Caiyeon** [comment]
The issue isn't just purity, it's the fact that I know people will use it for sake of convenience if they can. And they won't realize they're potentially leaking unseal tokens in the process. I will consider this, since nomad apparently offers bare bones vault integration.

**Comment by Caiyeon** [comment]
I presume nomad allows injecting the token into the deployment config file `config.hcl`?

**Comment by justenwalker** [comment]
I agree it is a bit silly that Nomad doesn't support AppRole since it is specifically designed for this purpose. Nevertheless, Nomad manages the whole token lifecycle on behalf of the hosted application and provides a few avenues for interacting with vault:

1. (default) Read the secret file containing the raw vault-token. This is found under `${NOMAD_SECRETS_DIR}/vault_token`
2. Optionally, have Nomad set the`VAULT_TOKEN` environment variable with the raw token
3. Nomad can also reach out to vault and populate config files using consul-template; never even having the application know that Vault even exists.

I suggest that, instead of (or in addition to) having the raw token in the `config.hcl` directly, allow users to point it at a file instead, and read the raw token from that file. That level of indirection provides the easiest avenue for users to integrate directly with Nomad's vault support. Otherwise, everyone has to template values into their config in some way, which is not ideal.

See Also:

- [vault Stanza](https://www.nomadproject.io/docs/job-specification/vault.html)
- [template Stanza](https://www.nomadproject.io/docs/job-specification/template.html) | [consul-template README on secrets](https://github.com/hashicorp/consul-template#secret)

**Comment by Caiyeon** [comment]
I added `nomad-token-file` as a cmd line arg. This should be what you're looking for. If you want to take the build for a spin, artifacts can be found here https://circleci.com/gh/Caiyeon/goldfish/437#artifacts/containers/0

Otherwise, they should be included in the next release (but I'm not sure when that'll be)

Cheers

**Comment by justenwalker** [comment]
Nice, Thanks!
