### ISSUE TITLE
Feature Request: Browser Back Button Should Go Back in Secrets Path Hierarchy 

### ISSUE THREAD

**Issue by ecliptik** [Caiyeon/goldfish#151]
When browsing Secrets, going back to the previous path is not intuitive. Clicking the Browsers Back Button would assume to go back in the Secrets path you're viewing, but instead goes back to the last link viewed in Goldfish.

For example if I'm viewing the Secrets path `secret/devops/admin` and use the Browser Back Button I would expect to see the `secret/devops` screen, but instead it would take me to the Transit Tools Page which I was viewing before Secrets.

Steps to illustrate:

1. Log into Goldfish and go to Tools/Transit

2. Go to Secrets, which has a `devops` path:
<img width="205" alt="screen shot 2017-08-28 at 2 02 21 pm" src="https://user-images.githubusercontent.com/1261742/29793738-e8e49966-8bf9-11e7-88cf-47b659f0d331.png">

3. Click `devops` path, so now we're in `secrets/devops`,
<img width="246" alt="screen shot 2017-08-28 at 2 07 03 pm" src="https://user-images.githubusercontent.com/1261742/29793803-32ba70b0-8bfa-11e7-9ff7-1d48a0724c05.png">

4. Click `admin` path, so now we're in `secrets/devops/admin`
<img width="335" alt="screen shot 2017-08-28 at 2 07 44 pm" src="https://user-images.githubusercontent.com/1261742/29793832-4b6b215e-8bfa-11e7-80ab-7cf03c682831.png">

5. Now say we want to go Back to `secrets/devops` to look at the `test` secret. Clicking on the the Browser Back button does not go to `secrets/devops`, but instead goes back to Transit
<img width="650" alt="screen shot 2017-08-28 at 2 08 38 pm" src="https://user-images.githubusercontent.com/1261742/29793862-7390d804-8bfa-11e7-8f57-d297cd1eafca.png">

I know you can use the Green Path UI button to go back in a path, but it's non-intuitive and even after using Goldfish for a few months I still accidentally click the Browser Back Button and have to re-navigate secrets paths to get back to where I was. Other engineers who are using Goldfish also have similar issues and this is the first complaint they have when using Goldfish.

This behavior happens on both Chrome and Safari and doesn't seem to be a browser specific thing.

**Comment by Caiyeon** [comment]
The only way to implement this that I know of is to include the current secret path in the url as a query parameter. This would then mean that secret paths would leak through browser history. But I suppose secret paths shouldn't be secret anyway, and the client's browser history is something that shouldn't be compromised anyhow.

I'll think about it, but I am quite busy for this week and possibly the next

**Comment by ecliptik** [comment]
That does make it much more difficult from a security perspective if you want to hide the path.

I think having the secret path in the URL as a "feature" since I frequently point co-workers to secret paths. Currently I do a "go to `secret/applications/this-app/development/key` in the UI" and hope they navigate to the right place and update the correct path/key, when copying/pasting a definitive URL to a path is much easier and more of a guarantee.

This isn't a huge priority, meant to put it in for a while (hence the other issues as well) and finally got around to doing it today. Thank you for your work.

**Comment by Caiyeon** [comment]
I firmly believe paths should never contain any secret info, but I don't expect everyone to agree. I'll leave this ticket open and keep it in mind

**Comment by justyns** [comment]
What about storing a short-lived secret in vault that contains the full path to the secret?  This is what I'm thinking:

* User visits secrets page for `secret/bulletins/test`
* goldfish creates a new secret at `secret/goldfish/urls/ABC123` with the content `url=secret/bulletins/test`
* User's browser url changes to `/#/secrets/ABC123`
* Vault expires the secret after whatever the ttl was set to.  This would let the user copy/paste the browser url to coworkers/etc to view a specific secret.

**Comment by Caiyeon** [comment]
That would be too much caching for something that should be fast. If the round trip to vault is already slowed by infrastructure (e.g. load balancers or proxies) this would just be a nightmare.

Vault's documentation actually include secret paths in their api calls for reading secrets. This is good enough of a reason for me to allow the same. I'll see what I can come up with
