### ISSUE TITLE
Feature Request: Multi-Select Key Deletion in Secrets Path

### ISSUE THREAD

**Issue by ecliptik** [Caiyeon/goldfish#153]
When removing keys from a Secrets path, it would be nice to have a Multi-selection option so a single, multi, or all keys could be deleted from a path in one action.

For example if when completely removing all keys for a path (which is required in order to delete a path), I have to click the Red Trash icon for every key. For a path with a hundred keys this can take a while (using the vault-cli is also an option, but having it as an action is Goldfish would make it much more accessible for new users).

Having a Select All checkbox to select/unselect all keys and then prompt for a "Really Delete X keys?" option would also be helpful.

**Comment by Caiyeon** [comment]
Multi select should be a thing. The only hard part is finding the right place to but that delete/confirm button

**Comment by Caiyeon** [comment]
I have a draft deployed on the demo https://vault-ui.io/#/secrets

Let me know if this is intuitive enough. I wanted to avoid checkboxes (they're quite ugly)

**Comment by ecliptik** [comment]
That looks really good. Tested out select-all and multi-select and it works as I would expect it too. Thank you.
