### ISSUE TITLE
Issue running the server 

### ISSUE THREAD

**Issue by krism74** [Caiyeon/goldfish#154]
Hi, newb here trying to use this repo and running the server in dev mode throws up this error

Any suggestions will be really helpful

thanks in advance

-----------------------------------

# command-line-arguments
./server.go:172: cannot use handlers.Health() (type "github.com/caiyeon/goldfish/vendor/github.com/labstack/echo".HandlerFunc) as type "github.com/goldfish/vendor/github.com/labstack/echo".HandlerFunc in argument to e.GET
./server.go:173: cannot use handlers.VaultHealth() (type "github.com/caiyeon/goldfish/vendor/github.com/labstack/echo".HandlerFunc) as type "github.com/goldfish/vendor/github.com/labstack/echo".HandlerFunc in argument to e.GET
./server.go:174: cannot use handlers.Bootstrap() (type "github.com/caiyeon/goldfish/vendor/github.com/labstack/echo".HandlerFunc) as type "github.com/goldfish/vendor/github.com/labstack/echo".HandlerFunc in argument to e.POST
./server.go:176: cannot use handlers.Login() (type "github.com/caiyeon/goldfish/vendor/github.com/labstack/echo".HandlerFunc) as type "github.com/goldfish/vendor/github.com/labstack/echo".HandlerFunc in argument to e.POST

**Comment by Caiyeon** [comment]
Seems like your go environment is messed up. You'll have to set your gopath properly and use go get to fetch the repo and place it in the right place. `github.com/goldfish` is not proper structuring

**Comment by krism74** [comment]
Thanks much, that was the issue, the server starts up fine now. Is there a link for detailed documentation that I am missing. 

How do i get to the UI page once I start up the server.go?

**Comment by PanosKou** [comment]
Hello! Newb here as well! I have the exact same issue! did the above issue get resolved? If so, could you please share some more details? Thank you in advance.

**Comment by Caiyeon** [comment]
https://github.com/Caiyeon/goldfish#running-locally
