### ISSUE TITLE
Github auth type login is broken in v0.7.0

### ISSUE THREAD

**Issue by ivanovs-4** [Caiyeon/goldfish#155]
Can't use authentication type `Github` in Goldfish frontend:
`Vault: missing client token`

![selection_001](https://user-images.githubusercontent.com/1263519/30143574-fdd9fa5c-939f-11e7-86a5-1fa7c4bcc5ba.jpg)

Though with console client it works:
```
vault auth -method=github token=***
Successfully authenticated! You are now logged in.
The token below is already saved in the session. You do not
need to "vault auth" again with the token.
token: *****

token_duration: 2764800
token_policies: [default]
```

**Comment by Caiyeon** [comment]
If you switch the auth type to `Token` and use the client token that vault CLI gave you, will it work?

Just eliminating the problem down to github specifically

**Comment by Caiyeon** [comment]
This has been fixed in `master`. It will be included in the next minor/major release. Apologies for the inconvenience.

**Comment by ivanovs-4** [comment]
Yes, it works with the auth type `Token` and token from vault CLI.
Thank you for awesome tool!
