### ISSUE TITLE
is nodejs required for PROD ?

### ISSUE THREAD

**Issue by joeblew99** [Caiyeon/goldfish#157]
Just wondering as this is a deal breaker for us.

**Comment by gesellix** [comment]
You can see inside the [Dockerfile](https://github.com/Caiyeon/goldfish/blob/master/docker/Dockerfile.compose) that there's no dependency on Node.js. Goldfish is single Golang binary including the static assets.

**Comment by joeblew99** [comment]
thankyou - shoudl have thought to look there.
