### ISSUE TITLE
Feature request: Access log as report

### ISSUE THREAD

**Issue by crajeshbe** [Caiyeon/goldfish#158]
Can we please add new page/section that shows information from the credential access log?

**Comment by Caiyeon** [comment]
Which credential access log are you referring to?

**Comment by crajeshbe** [comment]
@Caiyeon,

I'm referring to the information that is being written to the audit backend.

**Comment by Caiyeon** [comment]
There are no current plans to integrate with audit backends. I feel that it's infeasible for goldfish to ever be as good as any of the other solutions to auditing (ELK, for example).
