### ISSUE TITLE
Freeze when unknown parameter found in config

### ISSUE THREAD

**Issue by Albibek** [Caiyeon/goldfish#159]
Steps to reproduce:
* add unknown value to config
```
listener "tcp" {
  address       = ":443"
  tls_cert_file = "valid.crt
  tls_key_file  = "valid.key"
  invalid = "value"
}
```
* goldfish hangs up, not reporting any configuration errors or continuing to work

**Comment by Caiyeon** [comment]
I see the problem. It's a blocked channel that was never received from.
You can expect a fix soon.

Thanks for reporting this!
