### ISSUE TITLE
v0.7.1 entering a secret path no longer works

### ISSUE THREAD

**Issue by Mike-Dunton** [Caiyeon/goldfish#160]
Hi I just released v0.7.1 and I am having issues navigating to certain secret paths via the input box on the secrets page. 

If I go to the link directly for example. 
```
https://vault-ui.example.com/#/secrets?path=%2Fsecret%2Fmypath%2F
```

I can see the secrets and navigate around successfully. 

However if I go to the secrets page and enter the path of a secret directly into the box and hit enter I am not navigated to that secret path.

Let me know if you need more details. I am about to dive into the vue code to see if I can find the issue.

**Comment by Mike-Dunton** [comment]
It is like as soon as I get a Vault:  permission denied error I couldn't navigate anymore. 

In my environment not everyone has access to all the secrets.

**Comment by Caiyeon** [comment]
There is a bug where the entered path isn't always recognized and updated. I only found out recently.

The vault permission denied however should have came straight from vault. It looks like you have a `/` at the end of your path in url. Was the path in the secret page also trailed with a `/`?

**Comment by Caiyeon** [comment]
This should fix the problem https://github.com/Caiyeon/goldfish/releases/tag/v0.7.2-rc1

Let me know if it does/doesn't work :)

**Comment by Mike-Dunton** [comment]
Cool. I'll try this out later. The permission denied was intentional, but probably did not correlate with the issue.

**Comment by Caiyeon** [comment]
Latest: https://github.com/Caiyeon/goldfish/releases/tag/v0.7.3
Apologies for the buggy release lately
