### ISSUE TITLE
panic: could not locate box "public"

### ISSUE THREAD

**Issue by InTheCloudDan** [Caiyeon/goldfish#162]
I built the vagrant box with golang 1.9 and npm 5.4.2 because vault was failing to compile with 1.8 and the npm run dev was failing with npm < 5. Now the UI comes up and it looks like everything compiles with go but when I try to start it I'm getting:

```
panic: could not locate box "public"
```

Also it doesn't look like that panic gets logged into journalctl in the vagrant box or anywhere else I could see from initial look. I had to manually start the application to find the cause.

**Comment by Caiyeon** [comment]
Thank you for the report, I'll take a look when I get a chance. The last dev that worked with the vagrant box was months ago and it hasn't been properly maintained in awhile

**Comment by avanier** [comment]
I'll chime in as well. I tried building with `yarn 0.21.3`, `node v6.9.5`, and golang `v1.8` and `v1.9` and I'm getting the same error on all versions from `head @ 54678b2` all the way back to `v0.6.0` and I'm getting the same error. I'm on Linux x64.

**Comment by Caiyeon** [comment]
The vagrant box has not be updated. I don't have the time to update it as of now, but I'll keep this issue open as a reminder to fix it. There's no point in further comments so I'm locking this. The local development steps (without vagrant) are still valid and should be used for now.

**Comment by Caiyeon** [comment]
b626fba and a9ac3d0 has fixed the vagrant build. Running `vagrant up` should work now. Note that the port changed from `8001` to `8080` to conform with the local development settings.
