### ISSUE TITLE
UI: After Saving Secret - Up Path Button No Longer Works

### ISSUE THREAD

**Issue by ecliptik** [Caiyeon/goldfish#163]
Goldfish Version: 0.7.2
Browser: Safari 11

Issue: After adding a new secret in a path and saving it, a green Success Box appears, but trying to click the Green Up Path button no longer works. If a secret is not saved the Green Up Path button works. Clicking the back button in the browser works.

To reproduce:
1. Navigate to existing secret path
2. Click Add Secret button
3. Add a secret, press enter
4. Fill in Key and Value and click Save Secret button
5. Get Success! response
6. Attempt to go back up in the path clicking the Green Up button

**Comment by Caiyeon** [comment]
I see the issue. Thanks for the report! Should be fixed soon.
Apologies for the buggy releases, that secret path history rework really screwed some things up

**Comment by Caiyeon** [comment]
Latest: https://github.com/Caiyeon/goldfish/releases/tag/v0.7.3
