### ISSUE TITLE
Support for secrets that contain newlines

### ISSUE THREAD

**Issue by lucymhdavies** [Caiyeon/goldfish#165]
<img width="752" alt="screen shot 2017-10-02 at 16 54 15" src="https://user-images.githubusercontent.com/1116529/31086879-f7125366-a792-11e7-9e39-f3153e028704.png">

This was created with

```
$ vault write secret/lucytest foo="far
> far
> away"
Success! Data written to: secret/lucytest

$ vault read secret/lucytest
Key                 Value
---                 -----
refresh_interval    768h0m0s
foo                 far
far
away
```

**Comment by brandonblock** [comment]
I'm running into this issue but with a private/public certs. Line breaks are not persisting when storing the cert through goldfish so when the secret is fetched from vault it's not recognizable as a valid cert.

**Comment by Caiyeon** [comment]
Viewing and editing has both been implemented just now. You can check out the demo if youd like https://vault-ui.io/#/secrets?path=secret%2Fmultiline
Should be in the next release.
Shift+enter to start multi-line editing
The only drawback is that pressing enter to insert a key now needs two enter key presses. I believe it's minimal.
