### ISSUE TITLE
Cannot compile functional binary locally

### ISSUE THREAD

**Issue by sircinnamon** [Caiyeon/goldfish#166]
After cloning repo, build creates binary but the UI seems to not build correctly. Local binary is around 8 mb smaller than the release binary provided for download. I would like to replicate the release binary locally for security purposes. Documentation on how to do so would be very helpful.

Additional info: When running the locally generate binary file, it claims to bootstrap vault but fails on: `"panic: could not locate box "public""`

If run in dev mode, starts up but returns a 404.

**Comment by Caiyeon** [comment]
Static assets (HTML, JS, CSS, etc.) are compiled into the binary. 
So you'll need npm to build the binary (not just golang)

See here for more details:
https://github.com/Caiyeon/goldfish/blob/master/build.sh
