### ISSUE TITLE
v0.7.3 binary shows v0.7.2 as version number.

### ISSUE THREAD

**Issue by lvets** [Caiyeon/goldfish#171]
Downloading the v0.7.3 binary from https://github.com/Caiyeon/goldfish/releases/download/v0.7.3/goldfish-linux-amd64 results in a binary with version v0.7.2 shown in the UI.

**Comment by Caiyeon** [comment]
I just tried deploying this exact binary, and it shows as v0.7.3
It is likely your deployment configuration steps are executing the wrong binary, or not downloading the right binary

**Comment by lvets** [comment]
My bad, it's actually the Vault version that's displayed.
