### ISSUE TITLE
approving requests... where do i get my unseal token?

### ISSUE THREAD

**Issue by airtonix** [Caiyeon/goldfish#173]
Assumed this would be my token "goldfish"... turns out. no it's not.

It's not obvious where I get this from. Is it generated, do i click a button?

**Comment by zerkms** [comment]
It is a token you obtain during vault initialisation.

**Comment by Caiyeon** [comment]
Indeed. The unseal tokens are just vault unseal keys. They'll be reworded in the next release for clarity.
