### ISSUE TITLE
Does initialization required every restart?

### ISSUE THREAD

**Issue by zerkms** [Caiyeon/goldfish#176]
At the moment, every time I restart the goldfish application - it requires the wrapped approle token.

Is it expected to be like that?

**Comment by zerkms** [comment]
I found the answer here https://github.com/Caiyeon/goldfish/blob/7ffb85163adc0bb1e5f79df45f20f3906013cc00/docker/entrypoint.sh#L32

**Comment by Caiyeon** [comment]
Yes, this is expected. If you relaunched goldfish with the same approle token, then the security model is compromised. You risk exposing unseal keys by reusing approle tokens
