### ISSUE TITLE
Search secrets

### ISSUE THREAD

**Issue by ivangretsky** [Caiyeon/goldfish#180]
Good day!
The project looks awesome! Thanks for doing it!

I have played with online demo and read the docs, but did not find an option to search secrets by values and/or keys. It is an extremely important feature when having a lot of secrets. Some key/value pair would be added only for the search purpose.

Trying to make a team keepass analog here))

**Comment by Caiyeon** [comment]
Recursively searching backends for secrets is a non-trivial problem considering the granularity of policies that vault prides itself in. I'm not sure if I have seen a good use case that requires a search function. It's important to remember that vault is not keepass, it's a secret management system, not a password management system

**Comment by ivangretsky** [comment]
Thanks for the quick reply, @Caiyeon. The issue is closed, so can I ask a little off-topic question... I am indeed in a search for good open source team password and/or secret management solution. Actually I do not really know the difference between the two. Could you please help me figure it out.

After some reading I came to understand that password management system is kind of a subset of secret management. Password management system only stores secrets to be read by allowed humans, and secret management system can serve both humans and programs. Plus password management systems add features like autofill. 

If that is correct Vault with Goldfish seems to me to be a good replacement for a team password management system like Lastpass. Could you please give me some wisdom on the subject. What am I missing, why Vault + Goldfish will not suite me or will be not the best choice?

**Comment by Caiyeon** [comment]
Password management tools ensure that users (even admin users) cannot see any other user's passwords. Nor would they have a reason to do so. Secret management tools handle secrets that are likely shared with a group of people, e.g. database passwords. This means there is ultimately a person (or a quorum of admins, in the case of vault) that are able to view everyone's secrets. Therefore, Vault is unsuitable for personal password management.
Hope this helps
