### ISSUE TITLE
Svg logo does not scale well in firefox

### ISSUE THREAD

**Issue by ivangretsky** [Caiyeon/goldfish#183]
Svg logo shows well in Chrome, but not in Firefox (where it seems like there is no logo at all). Seems like it is this bug: https://stackoverflow.com/questions/31087215/svg-image-inside-of-svg-does-not-scale-in-firefox. Sorry for not making a pull request)

**Comment by Caiyeon** [comment]
Possibly related to or solved by #168 which I haven't found the time to fully test yet

**Comment by Caiyeon** [comment]
This should be fixed with the merge of the previously mentioned PR, and will be included on the next release. If it still shows unexpected behavior on the next release, please feel free to reopen this issue.
