### ISSUE TITLE
Feature request: configurations for multiple login paths

### ISSUE THREAD

**Issue by nickwales** [Caiyeon/goldfish#185]
We run multiple LDAP services so they are mounted on e.g.

ldap/team1
ldap/team2

When clicking on the LDAP tab I get a couple errors pop up with 'Error 500'. From the logs Goldfish 0.7.4 seems to just be looking up the default paths.

`path":"auth/ldap/users/","data":null,"remote_address":"127.0.0.1","wrap_ttl":0,"headers":{}},"response":{"data":{"error":"hmac-sha256:<redacted>"}},"error":"1 error occurred:\n\n* unsupported path"}`

**Comment by Caiyeon** [comment]
Indeed, goldfish currently assumes every login path is default. The code structure should make it easy to add a list of login methods in goldfish runtime config (the secret inside vault), and then offer an option for users to choose which path they're logging into. Unfortunately I'm too busy to implement this at the moment.
