### ISSUE TITLE
Goldfish does not support being run behind a proxy with a changed url

### ISSUE THREAD

**Issue by RoelVanNyen** [Caiyeon/goldfish#186]
If I run goldfish as : http://somedomain.com/ it will work.
If I run goldfish under http://somedomain.com/goldfish/ using a proxy it will not work because for example:
Tries to find asset under https://somedomain/assets/js/app.752d3f92b7071cf0482d.js instead of http://somedomain.com/goldfish/assets/js/app.752d3f92b7071cf0482d.js

For reference, in my case I`m trying to run it on DC/OS.

**Comment by Caiyeon** [comment]
This is not a problem with proxies. The assets packed by webpack are statically set in routing, therefore changes in url prefix will cause issues. If there's a magical way for routing to be dynamic, pull requests would be welcomed. Manual workarounds can be achieved by building the binary locally with the prefix in webpack configurations

**Comment by moneydance** [comment]
I believe setting the webpack output's publicPath to be relative like so './' would fix my issue.

**Comment by laerus** [comment]
fix his please <3
