### ISSUE TITLE
Feature request: highlight changes in requests

### ISSUE THREAD

**Issue by lucymhdavies** [Caiyeon/goldfish#192]
e.g. currently, requests just show the two versions side by side.
(you're using highlight js for this?)

Would be nice if we could get diffs highlighted.

**Comment by Caiyeon** [comment]
It indeed would be nice. I wanted to try this when I imported highlightjs but couldn't find a way to do so. Pull requests are welcomed.

**Comment by Caiyeon** [comment]
Diffs have been added, but syntax highlighting (via diff2html) seems unsupported in node imports at the moment (the helper functions are not exported). Best I can do is a toggle for now, until some javascript wizard steps in and fixes it.

**Comment by lucymhdavies** [comment]
Tested out on https://vault-ui.io/

Looks pretty sweet! Thanks :)
