### ISSUE TITLE
Question : Update on Vault UI support for vault as a CA

### ISSUE THREAD

**Issue by abhishekraghav** [Caiyeon/goldfish#193]
Hi 

First of all thanks for this wonderful and cool UI for vault. I have only one question when can we expect the feature for Certificate management panel. This could be the coolest feature to be added.

One more thing, It would be great if this UI support revoking the certs, renewing the certs, monitoring the TTL of the certs so that the we could gracefully renew the certs once expired without any downtime.

Best.

**Comment by Caiyeon** [comment]
Features will never be given a deadline. Doing so would add too many problems. The Vault project itself never gives a solid deadline for features either. I can say that I've been too busy to implement such a management page in the short term.
