### ISSUE TITLE
More information in Slack notifications

### ISSUE THREAD

**Issue by lucymhdavies** [Caiyeon/goldfish#194]
Slack notification only has minimal information:

<img width="403" alt="screen shot 2017-11-02 at 09 37 38" src="https://user-images.githubusercontent.com/1116529/32319191-9b741c06-bfb1-11e7-9f9c-e29d3e8f99b1.png">

Some of the info you see in Goldfish, which would be useful to have in the slack notification:

e.g. request type, requestor, policy name

<img width="346" alt="screen shot 2017-11-02 at 09 37 44" src="https://user-images.githubusercontent.com/1116529/32319190-9b53aade-bfb1-11e7-9163-62ac9c48a4a3.png">

It might also be useful if the link in the slack notification sent you directly to the `/#/requests` endpoint, rather than just the home page.

**Comment by Caiyeon** [comment]
The lack of information is purposeful. I don't want information from an enterprise vault leaking into slack's servers (even if the information is technically non-secretive). The slack notification system does not have access to goldfish's address, and getting the link would require restructuring. I prefer to keep the slack package as minimal as possible for now.
