### ISSUE TITLE
A vote: should secrets be monospace or not?

### ISSUE THREAD

**Issue by zerkms** [Caiyeon/goldfish#195]
A
======
![screenshot from 2017-11-03 08-14-52](https://user-images.githubusercontent.com/302295/32345572-79a73b76-c06f-11e7-8d5c-6f5dbf49e443.png)
B
======
![screenshot from 2017-11-03 08-15-16](https://user-images.githubusercontent.com/302295/32345573-79d68a2a-c06f-11e7-8190-69a12c50d86b.png)

Please vote :-)

I personally go for **B**

**Comment by tbartelmess** [comment]
B

**Comment by zerkms** [comment]
It was a rejected PR btw: https://github.com/Caiyeon/goldfish/pull/189

**Comment by Caiyeon** [comment]
3 votes is close enough for me. I'll be reopening the PR and adding in missing code manually.
