### ISSUE TITLE
Delete confirmation

### ISSUE THREAD

**Issue by zerkms** [Caiyeon/goldfish#196]
https://github.com/Caiyeon/goldfish/issues/137 this issue added the confirmation on the secrets list, but when a particular secret is opened the `Delete secret` button deletes without confirmation.

Also, I think it would be the best for the confirmation to not be in the same place (but in a popup): if one accidentally double-clicks on delete, it still would make a lot of harm.

**Comment by Caiyeon** [comment]
Confirmation has been added. I agree that a confirmation modal would be much better. If a modal were to be made, it would have to universal for the entire site - in other words, it shouldn't just be a deletion feature. And as of now I don't foresee myself having the time to make such a feature.
