### ISSUE TITLE
New install failing on login: failed to find secondary index

### ISSUE THREAD

**Issue by snoby** [Caiyeon/goldfish#197]
Hello,
Version 0.7.4 and connecting it to an HA vault cluster fronted by an ELB.  I followed the setup instructions ( i believe) and I'm receiving this error on  initial login:
```
Error: 500
Error making API request. URL: PUT https://vault.int.example.com:8200/v1/auth/approle/login Code: 400. Errors: * failed to validate SecretID: failed to find secondary index for role_id "goldfish"
```
Still digging around to fully understand what all this means.

**Comment by Caiyeon** [comment]
This is vault telling you it didn't find the role_id. You probably missed this step in the deployment process: `vault write auth/approle/role/goldfish/role-id role_id=goldfish`.

Alternatively, it could be related to this https://github.com/hashicorp/vault/issues/3344, but if it's vault-side there's nothing I can do.

The official approle API might be a good reference: https://www.vaultproject.io/api/auth/approle/index.html

**Comment by snoby** [comment]
I'm not 100% sure which step I missed but I went through the instructions again and executed the role-id command again then generated a new wrapped token and was able to login and init the system. 

THANK YOU!!!!!!!!!!
:-)
