### ISSUE TITLE
bulletins

### ISSUE THREAD

**Issue by frandriamora** [Caiyeon/goldfish#198]
Hi

For some reason the bulletin on the top left hand side does not work: Error 500 Invalid Path
It seems my vault setup does not have the required path; but I got no idea how to create it and what to put there. Any tip?

Frederic

Best regards

**Comment by Caiyeon** [comment]
Bulletins are a place where you can put any notices you want for people using vault, and it is optional. That is, if you are not interested in using it, then you can stop right here and let it error out harmlessly :)

The bulletins endpoint can be configured the runtime settings, as seen here: https://vault-ui.io/#/secrets?path=secret%2Fgoldfish

The `BulletinsPath`'s value leads to a vault generic backend point of your choice, which stores a list of bulletins that you may want to display to everyone. This can be seen here https://vault-ui.io/#/secrets?path=secret%2Fbulletins%2F

You will of course, have to give every user the rights to list and read this path (and subpaths). Altering the default policy may be the best choice for this.

**Comment by frandriamora** [comment]
Thank you so much for that clear and quick answer. Much appreciated.

This tool rocks, by the way. I hope we will put it in production next week.

Cheers,
