### ISSUE TITLE
Return secrets sorted alphabetically

### ISSUE THREAD

**Issue by dswhite42** [Caiyeon/goldfish#200]
Goldfish seems to display secrets and paths/subpaths in an unsorted fashion.  It would nice if it displayed them in alphabetical order sorted by path or key  (either automatically, or as an option if you click on the headers to sort by that field ("Subpaths", "Key", etc.)

**Comment by Caiyeon** [comment]
Agreed. This should be an option. I am currently swamped with work outside of goldfish, but this functionality will be put on the roadmap.
