### ISSUE TITLE
Vault v0.9.0 support?

### ISSUE THREAD

**Issue by ecliptik** [Caiyeon/goldfish#202]
With the release of [Vault 0.9.0](https://github.com/hashicorp/vault/blob/v0.9.0/CHANGELOG.md) yesterday, will Goldfish work with it?

I'm assuming yes and may try out a test vault + goldfish but wanted to check if there are any known issues about upgrading the Vault version behind Goldfish.

**Comment by Caiyeon** [comment]
There seems to be no changes/deprecations in the change logs that would cause problems with goldfish. I am unable to find the time to preform an end to end testing with vault v0.9.0. However, I will leave this issue open in case anyone else finds any incompatibilities.
