### ISSUE TITLE
Hide secrets by default

### ISSUE THREAD

**Issue by nuriel77** [Caiyeon/goldfish#203]
This is a feature request: 
If possible to hide the secrets by default (e.g. *********) and have a button to show (and/or copy to clipboard). Something like Keepass does.
If the "view password" button is clicked - hide it again after n seconds.

**Comment by Caiyeon** [comment]
This has been discussed before, but displaying secrets only to star them out makes no sense to me. At the end of the day, vault is a secret management system, designed to share secrets within teams and sub-groups, and not designed for personal password management.
