### ISSUE TITLE
500 error after clicking Administration/Users/Userpass

### ISSUE THREAD

**Issue by pavelchalyk** [Caiyeon/goldfish#204]
Hi!
i cloned your repo and i'm running docker-compose with no modifications (no ssl, tls verify is disabled), after successful start i'm going to UI to Administration/Users/Userpass tab and get 500 error (the same exception i get on LDAP tab, 2 times):

`goldfish_1  | {"time":"2017-11-30T12:16:43.930384518Z","level":"-","prefix":"echo","file":"asm_amd64.s","line":"510","message":"[PANIC RECOVER] runtime error: invalid memory address or nil pointer dereference goroutine 15326 [running]:\ngithub.com/caiyeon/goldfish/vendor/github.com/labstack/echo/middleware.RecoverWithConfig.func1.1.1(0x2324398, 0x1000, 0xc420140000, 0x2f88bc0, 0xc4205167e0)\n\tF:/gopath/src/github.com/caiyeon/goldfish/vendor/github.com/labstack/echo/middleware/recover.go:75 +0x12a\npanic(0x180eae0, 0x2fd0440)\n\tC:/Go/src/runtime/panic.go:491 +0x283\ngithub.com/caiyeon/goldfish/vault.AuthInfo.ListUserpassUsers(0x1ac919d, 0x5, 0xc4204793a0, 0x8, 0x0, 0x0, 0x10, 0x170b640, 0xc420795101, 0xc4201e6b10, ...)\n\tF:/gopath/src/github.com/caiyeon/goldfish/vault/userpass.go:27 +0xb0\ngithub.com/caiyeon/goldfish/handlers.GetUserpassUsers.func1(0x2f88bc0, 0xc4205167e0, 0x0, 0x0)\n\tF:/gopath/src/github.com/caiyeon/goldfish/handlers/userpass.go:19 +0xb8\ngithub.com/caiyeon/goldfish/vendor/github.com/labstack/echo.(*Echo).add.func1(0x2f88bc0, 0xc4205167e0, 0x17, 0x1b2b7e8)\n\tF:/gopath/src/github.com/caiyeon/goldfish/vendor/github.com/labstack/echo/echo.go:467 +0x87\ngithub.com/caiyeon/goldfish/vendor/github.com/labstack/echo/middleware.SecureWithConfig.func1.1(0x2f88bc0, 0xc4205167e0, 0xd, 0x1b0308a)\n\tF:/gopath/src/github.com/caiyeon/goldfish/vendor/github.com/labstack/echo/middleware/secure.go:113 +0x2af\nmain.main.func1.1(0x2f88bc0, 0xc4205167e0, 0xc420675140, 0x2f7a980)\n\tF:/gopath/src/github.com/caiyeon/goldfish/server.go:135 +0xa4\ngithub.com/caiyeon/goldfish/vendor/github.com/labstack/echo/middleware.GzipWithConfig.func1.1(0x2f88bc0, 0xc4205167e0, 0x0, 0x0)\n\tF:/gopath/src/github.com/caiyeon/goldfish/vendor/github.com/labstack/echo/middleware/compress.go:92 +0x17f\ngithub.com/caiyeon/goldfish/vendor/github.com/labstack/echo/middleware.BodyLimitWithConfig.func1.1(0x2f88bc0, 0xc4205167e0, 0x0, 0x0)\n\tF:/gopath/src/github.com/caiyeon/goldfish/vendor/github.com/labstack/echo/middleware/body_limit.go:87 +0x19f\ngithub.com/caiyeon/goldfish/vendor/github.com/labstack/echo/middleware.RecoverWithConfig.func1.1(0x2f88bc0, 0xc4205167e0, 0x0, 0x0)\n\tF:/gopath/src/github.com/caiyeon/goldfish/vendor/github.com/labstack/echo/middleware/recover.go:82 +0xe1\ngithub.com/caiyeon/goldfish/vendor/github.com/labstack/echo/middleware.LoggerWithConfig.func2.1(0x2f88bc0, 0xc4205167e0, 0x0, 0x0)\n\tF:/gopath/src/github.com/caiyeon/goldfish/vendor/github.com/labstack/echo/middleware/logger.go:111 +0x121\ngithub.com/caiyeon/goldfish/vendor/github.com/labstack/echo.(*Echo).ServeHTTP.func1(0x2f88bc0, 0xc4205167e0, 0xc42016eef8, 0x1aa8e80)\n\tF:/gopath/src/github.com/caiyeon/goldfish/vendor/github.com/labstack/echo/echo.go:558 +0x108\ngithub.com/caiyeon/goldfish/vendor/github.com/labstack/echo.(*Echo).ServeHTTP(0xc42016eea0, 0x2f7a980, 0xc4201e20e8, 0xc420278e00)\n\tF:/gopath/src/github.com/caiyeon/goldfish/vendor/github.com/labstack/echo/echo.go:567 +0x228\nnet/http.serverHandler.ServeHTTP(0xc420195450, 0x2f7a980, 0xc4201e20e8, 0xc420278e00)\n\tC:/Go/src/net/http/server.go:2619 +0xb4\nnet/http.initNPNRequest.ServeHTTP(0xc42019c000, 0xc420195450, 0x2f7a980, 0xc4201e20e8, 0xc420278e00)\n\tC:/Go/src/net/http/server.go:3164 +0x9a\nnet/http.(*initNPNRequest).ServeHTTP(0xc42046e630, 0x2f7a980, 0xc4201e20e8, 0xc420278e00)\n\t<autogenerated>:1 +0x63\nnet/http.(Handler).ServeHTTP-fm(0x2f7a980, 0xc4201e20e8, 0xc420278e00)\n\tC:/Go/src/net/http/h2_bundle.go:5462 +0x4d\nnet/http.(*http2serverConn).runHandler(0xc4204041c0, 0xc4201e20e8, 0xc420278e00, 0xc42051ab20)\n\tC:/Go/src/net/http/h2_bundle.go:5747 +0x89\ncreated by net/http.(*http2serverConn).processHeaders\n\tC:/Go/src/net/http/h2_bundle.go:5481 +0x495\n\ngoroutine 1 [IO wait, 4 minutes]:\ninternal/poll.runtime_pollWait(0x7fa0dc8feeb0, 0x72, 0xffffffffffffffff)\n\tC:/Go/src/runtime/netpoll.go:173 +0x57\ninternal/poll.(*pollDesc).wait(0xc42046cf98, 0x72, 0xc420697700, 0x0, 0x0)\n\tC:/Go/src/internal/poll/fd_poll_runtime.go:85 +0xae\ninternal/poll.(*pollDesc).waitRead(0xc42046cf98, 0xffffffffffffff00, 0x0, 0x0)\n\tC:/Go/src/internal/poll/fd_poll_runtime.go:90 +0x3d\ninternal/poll.(*FD).Accept(0xc42046cf80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\tC:/Go/src/internal/poll/fd_unix.go:334 +0x1e2\nnet.(*netFD).accept(0xc42046cf80, 0x410256, 0x7fa0dc8bf8d0, 0x3)\n\tC:/Go/src/ne\n"}
`
please help, what i'm doing wrong?

**Comment by Caiyeon** [comment]
This is because LDAP and userpass are not configured in the docker setup. Unlike the `-dev` launch option, the docker setup does not set the vault instance up with these authentication backends.

In short, you are not doing anything wrong. This is supposed to happen. The docker compose setup is more of a demonstration on how to link vault to goldfish, rather than a complete demo.
