### ISSUE TITLE
approle token does not display the id

### ISSUE THREAD

**Issue by karstensi** [Caiyeon/goldfish#214]
Hi,

It is great to have the detailed overview in the administrator -> users pane. 
I have generated a approle, and when I view the token information on that I am missing the value of id. I was expecting that the id field in the information popup would contain the role_id value from
`vault read auth/approle/role/<role>/role-id`

**Comment by Caiyeon** [comment]
The info tab is populated with a tokens details as provided by vault. Therefore, if info is missing, vault simply didn't provide it. Retrieving extra info is nontrivial and will not scale well. As far as I know, vault's token lookup API does not respond with role ID, so there's nothing I can do here.
