### ISSUE TITLE
Hide passwords

### ISSUE THREAD

**Issue by dmc-user** [Caiyeon/goldfish#215]
Is it possible to the have secrets(keys) hidden with ****** ? So i would have to push a button to unhide the secret(or/and a button 'copy to clipboard'). 

This way other people looking at your screen behind you, cant see all the secrets.

**Comment by Caiyeon** [comment]
There are no plans to do this currently, although I believe it has been requested once before. Obscuring secrets from others' eyes is not in Vault's security model, and will not be goldfish's scope either.
