### ISSUE TITLE
start goldfish failed

### ISSUE THREAD

**Issue by xiaochao** [Caiyeon/goldfish#219]
go run server.go -dev

Starting local vault dev instance...
Your unseal token and root token can be found above
2017/12/19 16:25:11 [ERROR]: Launching goldfish: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/rekey/init
Code: 400. Errors:

* rekey already in progress
exit status 1

**Comment by Caiyeon** [comment]
I believe this occurs when you already have a vault dev instance running. Goldfish `-dev` option takes care of the lifecycle of a vault instance, so conflicts would occur.

**Comment by xiaochao** [comment]
As you say,it is my fault. Thank you for reply.
