### ISSUE TITLE
Feature request: RADIUS auth support

### ISSUE THREAD

**Issue by danielpgross** [Caiyeon/goldfish#221]
It would be great to be able to use [RADIUS-based auth](https://www.vaultproject.io/docs/auth/radius.html) to log into goldfish. This should be quite simple to implement, as it's essentially a variant of `userpass` auth. I'd be happy to contribute a PR.

**Comment by danielpgross** [comment]
Ah, I see now that it already seems to be implemented (e.g. [here](https://github.com/Caiyeon/goldfish/blob/master/config/dev.go#L24)). I can't seem to find any docs on how to use it, though.

**Comment by Caiyeon** [comment]
No that's just the development environment, which uses vault's modular method of starting up a dev instance.

Pull requests are welcome. The front-end code can be found here: https://github.com/Caiyeon/goldfish/blob/master/frontend/client/views/login/index.vue#L45
https://github.com/Caiyeon/goldfish/blob/master/frontend/client/views/login/index.vue#L66

Editing this should be easy (just a new option in multi-select, and a new albeit slightly redundant username and password form)

The backend code can be found here:
https://github.com/Caiyeon/goldfish/blob/master/vault/login.go#L47

This should also be easy, just add radius to the list of options, and a secondary key to `LoginMap` variable. For example, for userpass, the secondary key is just `password`

The only difficult part is testing. You can compile the binary yourself and test the login to make sure it works, or provide an integration test for the api handler function.

**Comment by danielpgross** [comment]
Thanks @Caiyeon for the reply and for your excellent work on the project. In the end, we've decided not to use RADIUS auth, so unfortunately I won't be able to contribute a PR for this in the near future.

**Comment by Caiyeon** [comment]
I see. In that case, when someone is able to test the functionality, they may reopen this or a new issue :)
