### ISSUE TITLE
User with read secrets access policy can't view it on UI

### ISSUE THREAD

**Issue by TolikT** [Caiyeon/goldfish#224]
Hi,

I created policy for read access:
```
path "secret/a*" {
  capabilities = ["read"]
}
```

And assigned it to the token with default policy. But when I login via UI with this token and try to see secrets, there is an "access denied" error.

Is it expected? Or is there any workaround to see secrets via Goldfish with read permissions?

I can retrieve values via vault directly
```
/ # vault read secret/a/b/c
Key                     Value
---                     -----
refresh_interval        168h0m0s
...
```
The deployment was done via latest docker settings.

**Comment by Caiyeon** [comment]
When you open secrets page, the token is used to read the default secret path. See `DefaultSecretPath` in https://vault-ui.io/#/secrets?path=secret%2Fgoldfish

You got an access denied error because presumably you set `DefaultSecretPath` to just `secret` rather than `secret/a/b/c`. If you want to be restrictive, try setting it to `cubbyhole`, which all users with default policy can access.

**Comment by TolikT** [comment]
@Caiyeon After your suggestion, I created another policy `secret-path-read`:
```
path "secret/goldfish*" {
  capabilities = ["read"]
}
```
Also I changed `DefaultSecretPath` to `secret/a/b/`
And `project-read` policy is:
```
path "secret/a/b*" {
  capabilities = ["read"]
}
```

User has `default`, `project-read`, `secret-path-read` policies. But still access is denied. Is here something wrong?

**Comment by Caiyeon** [comment]
Did you login? I'm not sure what's wrong here, but I can guarantee that reading secrets is not bugged :) Perhaps check the demo instance for inspiration on debugging?

**Comment by TolikT** [comment]
@Caiyeon I just looked on your demo version and figured out that there is also "list" capability exists. Without it "read" does not work . Now everything is ok.
Thank you for demo examples :)
