### ISSUE TITLE
license: move away from MPL-2.0

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [Caiyeon/goldfish#225]
I know it's a sensitive issue, but I can rather not comply with MPL and hence would not be able to use this great project. Could I kindly ask to move it to MIT or Apache 2.0?

**Comment by Caiyeon** [comment]
MPL-2 is the same license that the vault project itself uses. If you are able to use vault, you are able to use goldfish. In addition, my personal preference for side projects align with MPL rather than MIT/Apache. I do not foresee the license being changed in the near future.

**Comment by eljefedelrodeodeljefe** [comment]
Okay. Your preference is fine for me. I thought it was that way.

Just a comment, you wouldn't need to tie it to Vault though, because it would be possible to bundle Goldfish, but only use Vault. The thing I see critical about it is, that I am obligated to disclose altered code. That will definitely happen for consumers of one man OSS project, but very likely never for Vault.
