### ISSUE TITLE
Feature request: Add ability to optionally configure Proxy Path

### ISSUE THREAD

**Issue by aantono** [Caiyeon/goldfish#227]
In cases when Goldfish runs behind a proxy that does Path-based routing, it would be great if there was an ability to configure a proxy path (context path) to use, instead of doing complex URL-rewrite (which is very difficult with Vue.js type of async/ajax requests).

**Comment by Caiyeon** [comment]
Do you mean you want to run goldfish at address `domain.com/goldfish` instead of just `domain.com`?

**Comment by aantono** [comment]
Yep.

**Comment by Caiyeon** [comment]
There are no current plans to support path-based proxies, unfortunately.

**Comment by code-ape** [comment]
While I know it’s already been stated this feature is not planned to be added anytime soon, I wanted to simply put on record that I too would find this useful. I personally think it would be relatively simple change that would add a lot of value :)

**Comment by Caiyeon** [comment]
I'm sure some people would find this feature useful. However, I disagree that it would be a relatively simple change. The initial work may be cheap, but I am not willing to test this feature every release. On the off chance it breaks, an entire release would be trashed as a consequence.

The good news is that goldfish is open source, and everyone is absolutely welcome to fork and implement any feature they wish (provided they follow the very lenient MPL2 license)
