### ISSUE TITLE
Bug: Goldfish forgets the wrapper token on restart

### ISSUE THREAD

**Issue by Danpiel** [Caiyeon/goldfish#229]
### Bug report:

Vault version: 0.9.0

Goldfish version: 0.8.0

Operating system: Ubuntu 16.04

Steps to reproduce:

Using systemd unit to run Goldfish:
```
[Unit]
Description=goldfish
After=vault.service
Wants=vault.service

[Service]
ExecStart=/usr/local/bin/goldfish -config=/etc/vault/goldfish.hcl

[Install]
WantedBy=multi-user.target

```
Vault deployed with default ttl 8h, max_ttl 730h

Expected behaviour:

After server/service restart should be bootstrapped: true

Actual behaviour:

After server/service restart shows bootstrapped: false,
and asks for new token, can't read old one from previous setup

**Comment by Caiyeon** [comment]
Wrapped tokens can be only used once. That is the purpose of "wrapping" a token. Goldfish will never store files, and therefore when you restart it, it cannot remember anything from a previous launch. This is a security design. You will need to re-provide it with a new token every launch. This can be automated with an orchestration tool such as Terraform or a simple bash script.
