### ISSUE TITLE
Major BUG remove delete button for root token

### ISSUE THREAD

**Issue by semionk-jomedia** [Caiyeon/goldfish#230]
### Bug report:

Vault version:
0.9.0
Goldfish version:
0.8.0
Operating system:
ubuntu 16.4
Steps to reproduce:
login to to goldfish ---> users -->tokens --> load first page of tokens---> delete root token
Expected behaviour:
delete root token should not cause complete vault shutdown.
Actual behaviour:
root token gets deleted blocking vault completely, even generating new root token doesnt help.

### Feature request:

Is this a front-end feature or backend? (or both?)
Both
Description of feature:

if root token is deleted, vault locks its self and denies permission to do anything.
Generating a new root token using the unseal keys, wont work either completely blocks vault.

Issue is for goldfish to deny or remove button with ability to delete such token or other way of safe guarding vaults access.

Solution for fixing this was poor. Had to delete backend completely and re-initiate vault again using new backend data source.

Are you able to submit a pull request for this feature?
no

**Comment by Caiyeon** [comment]
Removing a root token is a perfectly legal vault procedure and does not lock down vault. I have done this in the past, and I have done it just now for a sanity check. I suspect that all your tokens were created from the root token without `orphan` property, therefore revoking the root token revoked all your tokens in tree-fashion. This is a vault system design.
