### ISSUE TITLE
Bug: goldfish only listens on ipv6, not ipv4

### ISSUE THREAD

**Issue by nergdron** [Caiyeon/goldfish#231]
### Bug report:
Vault version: Vault v0.9.1 ('87b6919dea55da61d7cd444b2442cabb8ede8ab1')
Goldfish version: v0.8.0
Operating system: Ubuntu 16.04
Steps to reproduce:

put address = "0.0.0.0:443" in the listener config.
run goldfish

Expected behaviour:
listens on both tcpv4 and tcpv6.

Actual behaviour:
see it's only listening on tcpv6 and not tcpv4.

```
# netstat -tlpn | grep goldfish
tcp6       0      0 :::80                   :::*                    LISTEN      7921/goldfish   
tcp6       0      0 :::443                  :::*                    LISTEN      7921/goldfish
```

**Comment by Caiyeon** [comment]
Even though it is listed as tcp6, goldfish will listen on both ipv4 and ipv6. This is something called a dual stack (iirc?) implementation. Although it depends on the platform, most platforms will support this.

As a short demonstration, you may notice that your browser is able to access the goldfish demo `vault-ui.io` but not `ipv6.google.com`.
