### ISSUE TITLE
Feature request: Revoke token on logout

### ISSUE THREAD

**Issue by michaeltravisuk** [Caiyeon/goldfish#232]
**Backend issue**

We are primarily using LDAP auth to generate tokens with Goldfish, but these do not expire on logout.  While this is understandable for token auth where the token may be reused, it would be useful for LDAP or other password based auth to treat the login session as the only time the token will be used and revoke the token on logout.  Maybe this could be added as a configurable option?

**Comment by Caiyeon** [comment]
Logging out is a client side action; ideally, the client should be able to log out even if vault is offline for some reason. That being said, I do believe a "Revoke this token" button should be available in the login page (not the top navbar).
