### ISSUE TITLE
Feature Request: Make token TTL configurable on login

### ISSUE THREAD

**Issue by michaeltravisuk** [Caiyeon/goldfish#233]
**Back end feature**

We give fairly generous maximum TTLs to our users generating tokens with LDAP auth for some of our other Vault login use cases, but in the case of Goldfish, this can lead to a single user generating many orphaned tokens if they login to the UI regularly, particularly if they use the UI's logout feature, which does not expire the token they were using.

The token-create Vault API endpoint allows the specification of a token TTL, which will be honoured in the case that it is below the maximum TTL.  Would it be possible to make the TTL for non token-based auth configurable in the Goldfish options?

**Comment by Caiyeon** [comment]
Vault docs state that you should can revoke the token when you know you are finished with the work, or save the token for reuse. Goldfish provides the token to you once when you log in for this purpose. There is no good place to put a TTL parameter, nor should there be a need to do so. The max_ttl should be configured to the point which it is comfortable for the administrators.
