### ISSUE TITLE
Error: 500 Vault response was nil

### ISSUE THREAD

**Issue by co1dhand** [Caiyeon/goldfish#238]
### Bug report:

Vault version: 0.9.1

Goldfish version:  0.8.0

Operating system: Centos 7

Steps to reproduce: followed the GitHub doc, copied and pasted the token on the web UI.K

Expected behaviour: binding and initializing the goldfish UI with Vault

Actual behaviour:
two error notifications appear:
Error: 500
Get http://172.0.0.1:8200/v1/sys/health?sealedcode=299&uninitcode=299: dial tcp 172.0.0.1:8200: i/o timeout

Error: 500
Vault response was nil. Please revoke token. If your vault cert is self-signed, you'll need to enable tls_skip_verify in goldfish config.

I've already added the tls_skip_verify =1 on my goldfish, here's copypasta:

listener "tcp" {
        address          = ":8000"
        tls_disable      = 1
        tls_autoredirect = 0
}
vault {
        address         = "http://172.0.0.1:8200"
        tls_skip_verify = 1
}

my current vault is running with a consul storage, here's my config:
storage "consul" {
  address = "127.0.0.1:8500"
  path = "vault"
}

listener "tcp" {
 address = "127.0.0.1:8200"
 tls_disable = 1
}

**Comment by Caiyeon** [comment]
This is not a bug, it's an exception thrown when vault responds with an empty body. Try using vault CLI on the same machine; could be your network configurations.

**Comment by co1dhand** [comment]
Hello again, you can close my issue, as it was a really dumb misconfig which I've fixed now, kudos for your creation.

**Comment by co1dhand** [comment]
Hello again, I've managed to fix my issue, though now I'm facing another issue, when I try to login with a token, it just dispays permission denied. I tried to lookup the logs and here's what I've got:


{"time":"2018-01-29T11:17:29.25065599+01:00","id":"","remote_ip":"172.16.42.8","host":"192.168.0.171","method":"POST","uri":"/v1/login","status":403, "latency":3271323,"latency_human":"3.271323ms","bytes_in":74,"bytes_out":37}

**Comment by Caiyeon** [comment]
https://github.com/Caiyeon/goldfish/wiki/Configuration#transit-encryption-optional

You can remove the `ServerTransitKey` from the runtime configurations.
