### ISSUE TITLE
Bug: permission denied on secret/goldfish

### ISSUE THREAD

**Issue by AFriemann** [Caiyeon/goldfish#239]
### Bug report:

Vault version: 0.9.3

Goldfish version: 0.8.0

Operating system: RHEL 7 (in Docker)

#### Steps to reproduce:

I set up goldfish as described in https://github.com/Caiyeon/goldfish/wiki/Production-Deployment

secret/goldfish (all left out are n/a or default):
```
BulletinPath secret/bulletins/
DefaultSecretPath secret/
UserTransitKey usertransit
```

auth/approle/role/goldfish:
```
period 24
policies [default goldfish]
secret_id_num_uses 1
secret_id_ttl 300
token_max_ttl 0
token_num_uses 0
token_ttl 0
```

sys/policy/goldfish:
```hcl
path "secret/goldfish" {
  capabilities = ["read", "update"]
}

path "transit/encrypt/goldfish" {
  capabilities = ["read", "update"]
}
path "transit/decrypt/goldfish" {
  capabilities = ["read", "update"]
}

path "pki/issue/goldfish" {
  capabilities = ["update"]
}
```

application config goldfish.hcl:
```hcl
    disable_mlock = 1

    listener "tcp" {
      address = "0.0.0.0:8080"
      tls_disable = 1
    }
    vault {
      address = "https://vault.blub"
      tls_skip_verify = 1
    }
```

Grab the wrapping_token with:

```bash
vault write -f -wrap-ttl=5m auth/approle/role/goldfish/secret-id
```

And "let the goldfish swim"

#### Expected behaviour:

Goldfish should "initialize" and then stay that way.

#### Actual behaviour:

Initialization works fine, however at the next attempt to read secret/goldfish it receives a "permission denied" from vault.

/v1/health endpoint returns permission denied as well and vault audit log shows requests to token (auth/token/lookup-self) that works for a while and then returns permission denied all of a sudden.

I can still login via token/github/etc but goldfish itself can't connect to vault anymore.

**Comment by Caiyeon** [comment]
You set the approle with 24 seconds TTL instead of 24 hours.

**Comment by AFriemann** [comment]
absolutely correct, works perfectly fine now. Thank you! 👍
