### ISSUE TITLE
Can no longer auth with ldap on vault

### ISSUE THREAD

**Issue by co1dhand** [Caiyeon/goldfish#240]
Is it normal that I can no longer authenticate users with LDAP using SSH/CLI on the vault server after setting up goldfish and initiating the goldfish server?

Though it does work like a champ on goldfish itself, I've also tried to use the genereated token on the goldfishUI and use it to authenticate myself on vault and it did work, though, as soon As I try
`vault auth method=ldap username=bob
` 
I get this:

```
Error validating token: Error making API request.

URL: GET https://127.0.0.1:8200/v1/auth/token/lookup-self
Code: 403. Errors:

* permission denied
```

**Comment by Caiyeon** [comment]
Goldfish does not change how vault behaves, nor can it. I would recommend double checking your policies and LDAP configuration
