### ISSUE TITLE
Bug: Dockerfile refers to wrong config file, should use docker.hcl than config.hcl 

### ISSUE THREAD

**Issue by vmahedia** [Caiyeon/goldfish#245]
### Bug report:
Dockerfile refers to wrong file. 

Vault version:
n/a

Goldfish version:
v0.8.0

Operating system:
Mac

Steps to reproduce:
docker run -it docker_goldfish:latest

Expected behaviour:
Should run the docker image.

Actual behaviour:
2018/02/15 20:28:53 [ERROR]: Launching goldfish: open /app/config.hcl: no such file or directory

**Comment by vmahedia** [comment]
Can I get a write access to send a fix?

**Comment by Caiyeon** [comment]
I think this bug only occurs when using docker alone, rather than docker compose.
No, write access will not be given, even for bug fixes. You can submit a pull request instead.
