### ISSUE TITLE
[ERROR]: Launching goldfish At 7:19: Unknown token: 7:19 IDENT https

### ISSUE THREAD

**Issue by Alexvianet** [Caiyeon/goldfish#249]
### Bug report:

Vault version: Vault v0.8.0 ('af63d879130d2ee292f09257571d371100a513eb')

Goldfish version: 2018/02/27 21:56:19 Goldfish version: v0.9.0

Operating system: Ubuntu 14

Steps to reproduce:
just start 
sudo goldfish -config=goldfish-config.hcl
Expected behaviour:
all ok 
Actual behaviour:
[ERROR]: Launching goldfish At 7:19: Unknown token: 7:19 IDENT https

### my goldfish-config.hcl:
```
listener "tcp" {          
  address       = ":80"         # listen on default https port 
  tls_disable   = 1       
}                         
vault {                   
  address       = https://vault-dev.net:8200
  tls_skip_verify = 1     
}  
```
### Feature request:

Is this a front-end feature or backend? (or both?)

Description of feature:

Are you able to submit a pull request for this feature?

**Comment by Alexvianet** [comment]
my https://vault-dev.net:8200 is available and in work for long time 
and https://github.com/Caiyeon/goldfish/wiki/Production-Deployment:
step 1 was successfully done.

**Comment by Caiyeon** [comment]
Line 7, char 19 of your config file; strings need to be enclosed by double quotation marks in HCL files.

**Comment by Alexvianet** [comment]
thanks my fail)
