### ISSUE TITLE
Bug: 500 invalid character '<' looking for beginning of value when accepting github policy change

### ISSUE THREAD

**Issue by dylanfoster** [Caiyeon/goldfish#251]
### Bug report:

Vault version: 0.9.4

Goldfish version: 0.9.0

Operating system: osx

Steps to reproduce:

1. Change a loaded policy in github
2. go to requests
3. enter commit sha
4. accept change
5. navigate to secrets

Expected behaviour: secrets page loaded without error

Actual behaviour: error is observed

**Comment by dylanfoster** [comment]
P.S. this just seems like a race condition of some kind. If you wait for ~5-10 minutes it goes away

**Comment by Caiyeon** [comment]
Hi there, I don't fully understand where the issue is occurring. Does this error show up as a toast message (top right corner) when you open secrets page? If so, what does this have to do with github policy changes?

**Comment by dylanfoster** [comment]
It does come up as a toast on the right. It shows up on all pages after a policy change. I'm sure what it has to do with github policy changes but that's when it shows up (after I accept)

**Comment by Caiyeon** [comment]
How many policies are being changed in the request? Can you provide a screenshot of the toast message?

**Comment by dylanfoster** [comment]
It's happened a few times. Once was with two policy changes (just minor edits) and once was three (with one deletion)

<img width="405" alt="screen shot 2018-02-27 at 5 16 20 pm" src="https://user-images.githubusercontent.com/5842737/36769122-2ccf3b6c-1bf7-11e8-93a0-2dc0dbf6e7ab.png">

It seems like an error for malformed html (I've seen similar issues in ember before but I'm not sure where

**Comment by Caiyeon** [comment]
I just performed the same steps on the public demo and could not reproduce the issue.

I have seen this exact error not in goldfish, but in a proxy situation where HTML was provided in an HTTP response when JSON was expected.

Do you have a proxy somewhere in this configuration?

**Comment by dylanfoster** [comment]
this was all in testing/investigaiche so I did have ngrok in front of vault (and sometimes goldfish) so it could be that

**Comment by Caiyeon** [comment]
Strange. Does the error show up right after you accept the change, or does it show up after you click on another navigation button (e.g. secrets)? Is there anything in chrome/safari console when this error is displayed?

**Comment by dylanfoster** [comment]
it shows up after I click on another menu item (secrets, login, etc)

<img width="563" alt="screen shot 2018-02-27 at 8 41 44 pm" src="https://user-images.githubusercontent.com/5842737/36770370-cc63b994-1bfe-11e8-9f54-992164077715.png">

**Comment by Sispheor** [comment]
Same here
```
2018/03/01 16:06:45 [ERROR]:  invalid character '<' looking for beginning of value
```

I'm using the conf provided in the docker compose example.

**Comment by Caiyeon** [comment]
Interesting, it's a backend issue? @Sispheor are you also using github requests? Are there any non-hcl files in the specified directory?

**Comment by Sispheor** [comment]
I re deployed from scratch and I'm not able to reproduce it again.

**Comment by Caiyeon** [comment]
Peculiar. @dylanfoster if you have the time, could you confirm if it is still reproducible after a redeploy from scratch?

**Comment by dylanfoster** [comment]
Mine actually resolved when I deployed it live (rather than with ngrok) so I'm pretty sure that was it

**Comment by Caiyeon** [comment]
Good to hear the source has been found. Please open a new issue if it shows up again.
