### ISSUE TITLE
Bug: Unable to enter wrapping token/login BEHIND NGINX

### ISSUE THREAD

**Issue by ytjohn** [Caiyeon/goldfish#253]
I'm sure I'm missing something, but everything "looks" correct following the production deploy instructions.

### Bug report:

Vault version: Vault v0.9.3 ('5acd6a21d5a69ab49d0f7c0bf540123a9b2c696d')

Goldfish version: 2018/03/06 00:36:32 Goldfish version: v0.9.0

Operating system: Ubuntu 16.04

Steps to reproduce:  Follow steps from [production install
(https://github.com/Caiyeon/goldfish/wiki/Production-Deployment)

```
listener "tcp" {
  address       = ":8443"       
  tls_disable = 1
}
vault {
  address       = "http://172.29.129.156:8200"
  tls_skip_verify = 1
  runtime_config = "secret/goldfish"
}
```

Expected behaviour:

On goldfish web ui, I would be able to enter a wrapping token at login page. Additionally, I would see a Session dropdown option.

Actual behaviour:

Login page presents a normal login page, but throws a 400 error and unable to login with any valid token.

![image](https://user-images.githubusercontent.com/163156/37007779-0ba1e22c-20ad-11e8-9b93-0767ef3950c4.png)

Additionally, if I specify a token on the command line, it does seem to be able to talk to the vault. If I provide a bad token, I get: `2018/03/06 00:39:02 [ERROR]: Bootstrapping goldfish Failed to unwrap provided token, revoke it if possible`.  With a valid token, I get the following:

```
ubuntu@certainty01:~$ ./goldfish -config=goldfishconfig.hcl -token=99d0c306-53a9-eedf-672b-fd94b8f45473
2018/03/06 00:42:52 [INFO ]: Server config reloaded
2018/03/06 00:42:52 [INFO ]: Successfully bootstrapped. Server token accessor: 36fd748a-8295-0812-3807-42eaafa11967
```

However, even with passing a valid wrapping token, I still get the same 400 errors as shown in the screen shot.

**Comment by ytjohn** [comment]
I figured part of this out.  I had been using nginx as a reverse proxy in front due to firewall reasons. However, once I ran sshuttle and made a direct connection, it started working. 

I need to figure out how to run this behind nginx.

**Comment by Caiyeon** [comment]
It appears that nginx is causing the issue? If this is the case, this issue is not related to goldfish.

**Comment by ytjohn** [comment]
I've now isolated to running it behind nginx (or probably any sort of front end webserver/load balancer).  I am attempting to see if I can get a working configuration. For some reason the parts that handle the session are not working. 

Does goldfish use websockets or any other interesting bits to get sessions going?

**Comment by Caiyeon** [comment]
I am not sure what you mean.

I would recommend against having a frontend/backend separation or a load balancer. Goldfish needs neither. It's plenty fast to be used even in a large enterprise scale. My online UI is quite fast and it's running on the lowest specs VM (and handling vault in the same machine). Load balancing will only cause problems :)

**Comment by ytjohn** [comment]
Thanks to an old PR of @ecliptik I did get this worked out.  I'm not actually doing load balancing, just letting nginx handle the root privilege/443 separation. I have vault and goldfish running on the same set of VMs. 

https://vault.example.com/v1 -> nginx reverse proxies this to vault (localhost:8200)
https://vaultui.example.com/ -> nginx reverse proxies this to goldfish (localhost:8000)

I'll post my config here in case anyone else is looking for this type of setup. 

```
   location ~ / {
      proxy_pass https://localhost:8000;
      proxy_set_header    Host                $host;
      proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
      proxy_set_header    X-Forwarded-Proto   $scheme;
      proxy_set_header    Accept-Encoding     "";
      proxy_set_header    Proxy               "";
      proxy_redirect      off;
    }
```

**Comment by Caiyeon** [comment]
Ah I see! Good to know it has been fixed
