### ISSUE TITLE
Bug: in 'edit secret' view, any 'x' button deletes last entry

### ISSUE THREAD

**Issue by stampycode** [Caiyeon/goldfish#254]
### Bug report:

`v0.8.0`

In the 'Edit Secret' view, when multiple secrets are visible, clicking the "X" button next to any line always deletes the last entry in the list, not the one that was clicked.

edit: This actually only seems to happen when the list is sorted by the Key or Value column.

**Comment by Caiyeon** [comment]
Can confirm, is reproducible. Will be fixed soon. Thanks for the report!
