### ISSUE TITLE
Hide unrelated options in the UI for regular users

### ISSUE THREAD

**Issue by laerus** [Caiyeon/goldfish#271]
### Feature request:

Is this a front-end feature or backend? (or both?):

frontend

Description of feature:

Hide the 'Bulletin/Administration/Tools' in the UI for users that don't have permission to access those.

Are you able to submit a pull request for this feature?

no

**Comment by Mike-Dunton** [comment]
Something similar was requested in the past and denied. 
https://github.com/Caiyeon/goldfish/issues/243

**Comment by laerus** [comment]
:cry:

**Comment by Caiyeon** [comment]
Yeah this is not possible to implement given the current vault api
