### ISSUE TITLE
Wiki update: use the newest version of vault commands

### ISSUE THREAD

**Issue by ORuban** [Caiyeon/goldfish#272]
Please change vault commands on [Production Deployment](https://github.com/Caiyeon/goldfish/wiki/Production-Deployment) wiki page.

- from `vault auth-enable approle` to `vault auth enable approle` 
- from `vault policy-write` to `vault policy write`

to get rid of warnings like 
`WARNING! The "vault policy-write" command is deprecated. Please use "vault policy write" instead. This command will be removed in Vault 0.11 (or later).`

Are you able to submit a pull request for this feature?
GitHub curently doesn't support PR to the wiki page

**Comment by Caiyeon** [comment]
Ah, thanks for the catch! Wiki has been updated.
