### ISSUE TITLE
Support for SSH secrets engine?

### ISSUE THREAD

**Issue by sujithktkm** [Caiyeon/goldfish#280]
Hello,

Does Goldfish support `ssh` secrets engine? I was unable to find a way to list secrets engines or create tokens for ssh roles (created in `ssh` secrets engine)

**Comment by Caiyeon** [comment]
Hi,

Goldfish can list secrets engines (the `Mounts` button on the left). However, goldfish can only write to secrets *after* reading them. I'm not sure if this is ok for ssh backends. If it is insufficient, pull requests are welcomed.
