### ISSUE TITLE
Correponding vault setup?

### ISSUE THREAD

**Issue by sokoow** [Caiyeon/goldfish#288]
Hey, it would be very handy to have a corresponding, full vault setup : so all policies that you have in demo ui dumped somewhere, mounts and so on. Is it around anywhere yet?

**Comment by Mike-Dunton** [comment]
I think this is what is used for the demo. https://github.com/Caiyeon/goldfish/tree/master/vagrant

Check out the vagrantFile

**Comment by sokoow** [comment]
ah nice one, thanks :)
