### ISSUE TITLE
Smarter policy filtering

### ISSUE THREAD

**Issue by Caiyeon** [Caiyeon/goldfish#31]
If a user searches for policies that match `foo/bar`, policies that allow access to `foo/*` should match. This should be implemented entirely in javascript on the client side

**Comment by Caiyeon** [comment]
This line is where a policy's details is compared against the search string. https://github.com/Caiyeon/goldfish/blob/master/frontend/client/views/admin/Policies.vue#L202

Right now it just does a substring match. But ideally, a substring `foo/bar` should match a policy that contains `foo/*` or `foo/b*` in the rules.

**Comment by Caiyeon** [comment]
Possible fix is to turn `foo/bar` substring into a regex
The regex would have to match `foo/bar`, `foo/ba*`, `foo/b*`, but not match `foo/b` or `foo/a*`
Because vault policies only allow glob characters at the end of the path, it should also not match `foo*`

Such a regex can be built by 
```regex
foo\/(bar|b\*|ba\*|bar\*)
```
Which is `foo/` + `(b* | ba* | bar*)`. Such a regex string can be built on the fly via vuejs compute function.

The name of the selection should also be renamed from substring to something that indicates it's no longer just searching for a substring. Smart match, perhaps.

**Comment by Caiyeon** [comment]
To do:
* [ ] Add a new selection of search type. So it'll be likely `substring`, `smart search`, `regex`
  * [ ] To do this, the current type variable of regex and substring may need to be more complex than a boolean
* [ ] Add some help messages describing what smart search is
* [ ] Add search function to use smart search when chosen

**Comment by yonniluu** [comment]
Added in: https://github.com/Caiyeon/goldfish/commit/bd2fe50986ffbc8d9327517fd54e92e0e0034a9a
