### ISSUE TITLE
Current install instructions do not work.

### ISSUE THREAD

**Issue by rbastic** [Caiyeon/goldfish#43]
rbastic@marvin:~/go/src/github.com/caiyeon/goldfish$ goldfish -dev -vault_token $(vault write -f -wrap-ttl=20m \
> -format=json auth/approle/role/goldfish/secret-id \
> | jq -r .wrap_info.token)
flag provided but not defined: -dev
Usage of goldfish:
  -addr string
    	Vault address (default "http://127.0.0.1:8200")
  -approle_path string
    	The login path of the mount e.g. 'auth/approle/login' (default "auth/approle/login")
  -config_path string
    	The vault path containing goldfish config data e.g. 'secret/goldfish' (default "data/goldfish")
  -role_id string
    	The role_id the secret_id was generated from (default "goldfish")
  -token string
    	Wrapping token that should contain a secret_id

I have followed the instructions completely. Looking forward to getting to try this out. I'm a Vault newbie, so help is appreciated!

**Comment by Caiyeon** [comment]
You seem to be using a version of goldfish that is quite a few versions old. Try a fresh pull or download the release

**Comment by rbastic** [comment]
Umm, not quite. Did you read the error? It says -dev is not an option. The instructions in the README clearly include a goldfish -dev command. 

So, I'm using the latest everything, but the instructions don't work.

When is the last time you attempted to reproduce those install instructions from scratch?

**Comment by rbastic** [comment]
If I instead try:

$ goldfish -token $(vault write -f -wrap-ttl=20m -format=json auth/approle/role/goldfish/secret-id | jq -r .wrap_info.token)
panic: Error making API request.

URL: GET http://127.0.0.1:8200/v1/data/goldfish
Code: 403. Errors:

* permission denied

goroutine 1 [running]:
github.com/caiyeon/goldfish/vault.init.1()
	/home/rbastic/go/src/github.com/caiyeon/goldfish/vault/vault.go:56 +0x5c2
github.com/caiyeon/goldfish/vault.init()
	/home/rbastic/go/src/github.com/caiyeon/goldfish/vault/vault.go:72 +0xa8
github.com/caiyeon/goldfish/handlers.init()
	/home/rbastic/go/src/github.com/caiyeon/goldfish/handlers/user.go:172 +0x4d
main.init()
	/home/rbastic/go/src/github.com/Caiyeon/goldfish/server.go:68 +0x44

**Comment by Caiyeon** [comment]
The last time I tried following the dev set from scratch was last night.
The reason I know your compiled binary is lower in version is because it does not include many of the new settings that I added around v0.2.3, not just -dev.

Here's what I get when I download the latest v0.2.5 release and run `--help`:
![image](https://cloud.githubusercontent.com/assets/6126493/26638193/61c5598e-45d6-11e7-8d9a-8128cb2616b1.png)

Note the difference in the list of options

**Comment by Caiyeon** [comment]
This does however, remind me that I should add a version option to just display the compiled binary's version. I'll add that on my to do list

**Comment by rbastic** [comment]
Sorry about the noise. I had indeed install'd an old version and my dev environment had changed in-between. Thanks for your help!
