### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by Caiyeon** [Caiyeon/goldfish#5]
A docker image is in construction `https://github.com/Caiyeon/goldfish/blob/master/docker/Dockerfile`
In order for this to work, it must be stacked with a vault version 0.7.0 (0.6.x will fail)
Once HashiCorp releases their official docker image for the new version, a stack with goldfish and vault will be released.

**Comment by blakestoddard** [comment]
Looks like the [0.7.0 image is out](https://github.com/hashicorp/docker-vault/tree/master/0.7.0), and the 0.7.1 one should be out shortly I'd imagine.

**Comment by Caiyeon** [comment]
Docker image is complete and works with vault 0.7.0
A docker stack file should be tracked separately
