### ISSUE TITLE
LDAP support

### ISSUE THREAD

**Issue by johnjelinek** [Caiyeon/goldfish#54]
It would be awesome if goldfish supported an LDAP login method.

**Comment by Caiyeon** [comment]
@johnjelinek It's been integrated since https://github.com/Caiyeon/goldfish/issues/15
It's an option on the demo (but is obviously not hooked up to an actual LDAP)

Silly me just forgot to add it to the readme :) I'll get to that this evening.

Cheers,
Tony

**Comment by Caiyeon** [comment]
Updated readme accordingly in https://github.com/Caiyeon/goldfish/commit/6ce54700879e9e0af6a2ad1853f85b3c60ea5a64

**Comment by johnjelinek** [comment]
Sweet!
