### ISSUE TITLE
wrapping token is not valid or does not exist

### ISSUE THREAD

**Issue by johnjelinek** [Caiyeon/goldfish#60]
I run this to get my wrapping token:
```
vault write -f -wrap-ttl=20m -format=json auth/approle/role/goldfish/secret-id
```

I take the value and plug it in here as the `-vault_token` arg:
```
goldfish -goldfish_addr=https://0.0.0.0:443 -cert_file=/hab/svc/goldfish/data/cert.pem -key_file=/hab/svc/goldfish/data/key.pem -vault_addr=http://192.168.56.100:8200 -vault_token=fa9e53ae-63f2-6ebc-aac5-9603fc970f4e -approle_path=auth/approle/login -role_id=goldfish -config_path=secret/goldfish
```

What results is this `400` error:
```
* wrapping token is not valid or does not exist
```

How should I troubleshoot this? All of the preliminary vault setup for the approle has already been set up.

**Comment by johnjelinek** [comment]
oh, I'm just now seeing this message output as well ...
```
{"time":"2017-06-10T04:50:35.309053888Z","level":"-","prefix":"echo","file":"server.go","line":"143","message":"tls: failed to parse private key"}
```
I think the `* wrapping token` message may be a red herring.

**Comment by johnjelinek** [comment]
confirmed! Once the key was re-generated, the `wrapping token` error went away.

**Comment by Caiyeon** [comment]
If there was a panic above the 400 error like this: 
```
$ goldfish -dev -vault_token not_a_real_token
panic: Failed to unwrap provided token, revoke it if possible
Reason:Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/wrapping/unwrap
Code: 400. Errors:

* wrapping token is not valid or does not exist
```

That means goldfish was unable to unwrap the provided token. Note that this wrapping token needs to be regenerated every time you launch goldfish. It's even consumed when goldfish was not able to launch fully (e.g. if it stopped due to error reading key file).

Closing. Feel free to open another ticket if you find a goldfish-related error :)

**Comment by johnjelinek** [comment]
ya, I think the error in this scenario was misleading. It should've made the emphasis the bad certificate: `tls: failed to parse private key` rather than unwrapping the token.

**Comment by Caiyeon** [comment]
If a panic occurred, it would've never executed till line 143. Perhaps you launched goldfish twice with the same wrapping token, first led to tls error, second led to invalid wrapping token?
