### ISSUE TITLE
Panic unwrapping secret id when vault server has self-signed certificate

### ISSUE THREAD

**Issue by johnjelinek** [Caiyeon/goldfish#62]
My vault addr is HTTPS but with a self-signed certificate. When I start goldfish pointing to this vault, I see:
```
goldfish.default(O): panic: runtime error: invalid memory address or nil pointer dereference
goldfish.default(O): [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x756367]
goldfish.default(O):
goldfish.default(O): goroutine 1 [running]:
goldfish.default(O): github.com/caiyeon/goldfish/vault.StartGoldfishWrapper(0x7fff781dd9bb, 0x24, 0x7fff781dda0a, 0x8, 0x7fff781dd9ee, 0x12, 0x3f, 0x922a40)
goldfish.default(O): 	/hab/cache/src/go/src/github.com/caiyeon/goldfish/vault/vault.go:70 +0x237
goldfish.default(O): main.init.1()
goldfish.default(O): 	/hab/cache/src/go/src/goldfish/server.go:52 +0x43e
goldfish.default(O): main.init()
goldfish.default(O): 	/hab/cache/src/go/src/goldfish/server.go:146 +0x76
```
When I run `vault` CLI, I pass in the `VAULT_SKIP_VERIFY` environment variable. Can goldfish support this as well so it doesn't panic?

**Comment by Caiyeon** [comment]
Adding `-tls-skip-verify` cmd arg when launching goldfish will allow goldfish to talk to vault without verifying vault's certificate, much like how vault's CLI has a `-tls-skip-verify` option.

**Comment by johnjelinek** [comment]
I'll pass in the flag, but it shouldn't panic with a stack trace, maybe
catch it and show a friendly error.

**Comment by Caiyeon** [comment]
Agreed. Will reopen this until I fix in master branch. Looks like there may be one more minor release before 0.4.0
