### ISSUE TITLE
Prod deployment instructions result in error

### ISSUE THREAD

**Issue by rsteckler** [Caiyeon/goldfish#65]
First, thank you for Goldfish!  The live demo looks awesome and the project seems very well run.  

Primary issue is that I ran through the deployment instructions and everything appeared to succeed until I got to the last line:  
```
./goldfish \
-goldfish_addr ":443" -cert_file /path/to/certificate.crt -key_file /path/to/privatekey.pem \
-vault_addr $VAULT_ADDR -vault_token $VAULT_TOKEN \
-approle_path auth/approle/login -role_id goldfish \
-config_path secret/goldfish
```
I get the error:  ```Failed to read config secret from vault```

I'm able to read/write secrets from the vault CLI.  The vault is unsealed, etc.

Some suggestions for the deployment docs (and possibly things that I messed up because I deviated from the docs)
1)  In preparing the vault, the instructions assume that the goldfish source is local.  This line: ```vault policy-write goldfish $GOPATH/src/github.com/caiyeon/goldfish/vagrant/policies/goldfish.hcl```.  In my case, I just copied that single file from github to a local folder on my machine.

2) It wasn't clear from the instructions (and to a goldfish newbie) that the key that's output from step 2 is the input for step 3 ($VAULT_TOKEN).  Clarifying that, if it's correct, would be awesome.

3)  Goldfish version in step 3 is v0.3.0.  When I got the error, I tried bumping this to v0.3.3.  I still got the same error, but I'm guessing you want to bump the version number in the deployment instructions.

Thanks for any direction you can provide.  Apologies this is an issue instead of a PR :)

**Comment by Caiyeon** [comment]
That panic comes from goldfish being unable to read its runtime settings from path `secret/goldfish`

This path should be a generic backend endpoint that stores runtime settings that goldfish will read from every minute. Here's a list of keys that are valid https://github.com/Caiyeon/goldfish/wiki/Configuration#run-time-configurations

Part of the deployment script is to write this secret (but it only has to be done once) 
```
# production goldfish needs a generic secret endpoint to hot reload settings from. See below for explanations
vault write secret/goldfish DefaultSecretPath="secret/" TransitBackend="transit" \
UserTransitKey="usertransit" ServerTransitKey="goldfish" BulletinPath="secret/bulletins/"
```

You can go to https://vault-ui.io and read the secret/goldfish secret to see how it looks after goldfish has read from it

The wiki has been updated to 0.3.3. Thanks for that!

Cheers

**Comment by rsteckler** [comment]
I ran that command as part of the deployment script.  That key exists in the Vault database:
```
$ vault read secret/goldfish
Key              	Value
---              	-----
refresh_interval 	768h0m0s
BulletinPath     	secret/bulletins/
DefaultSecretPath	secret/
ServerTransitKey 	goldfish
TransitBackend   	transit
UserTransitKey   	usertransit
```

Is there some reason that I can pull that secret from the CLI, but Goldfish can't access it?

**Comment by Caiyeon** [comment]
Try this:
```bash
vault token-create -policy="goldfish"
export VAULT_TOKEN=<insert token from above>
vault read secret/goldfish
```

If the `goldfish` policy allows the newly created token to read this endpoint, that means the approle may be the problem. Or I am missing an edge case where the created token could be unwrapped but somehow not be used to read the secret.

**Comment by rsteckler** [comment]
My apologies for the run-around.  I re-ran the deployment instructions one-by-one and this time it worked.  I must have missed one, or missed one of the lines in the commands.

Thanks for your patient support.  Closing this out.
