### ISSUE TITLE
Remove Last Key from Secret - Error 400

### ISSUE THREAD

**Issue by Techcadia** [Caiyeon/goldfish#69]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Secrets Backend

##### GOLDFISH VERSION
```
v0.3.3
```

##### OS / ENVIRONMENT
CentOS 7.3

##### SUMMARY
When removing the last Key from a Secret goldfish won't let me save it.

##### STEPS TO REPRODUCE
1. in the secrets path click Add Secret Name it 'Blah'
1. add a key: 'foo' value: 'bar'
1. Save it
1. Now try to remove 'foo' from the Secret 'Blah'

##### EXPECTED RESULTS
This should succeed and the Secret should be removed since no keys remain

##### ACTUAL RESULTS
```
Error: 400
Vault: missing data fields
```

**Comment by Caiyeon** [comment]
This is actually the expected behaviour. Vault won't let you write to a secret with no data (even with `-f` option). It's vault itself that is returning the 400 error

The real problem here is that there's no delete function for secrets. This is an important operation and I will add it soon.

**Comment by Caiyeon** [comment]
Added in https://github.com/Caiyeon/goldfish/issues/71
