### ISSUE TITLE
404 or "message": "no found" errors?

### ISSUE THREAD

**Issue by klevermonicker** [Caiyeon/goldfish#70]
Your demo looks amazing! This is the tool I've decided to use for an interface to vault for anyone afraid of the CLI. However I'm having some issues with it giving me 404 or {"message": "Not Found"}

So I'm running it out of a user I created for this goldfish...I've got it as a systemd service and it starts up, but everytime I try to hit goldfish from the outside I get 

```404 file not found```

if I try to curl localhost from the host of course I get
```{"message":"Not Found"}```

Any ideas here?

I'm running this in AWS on ubuntu 16.04 with go 1.7

**Comment by Caiyeon** [comment]
`goldfish` executable serves static webpages from `public` folder of the working directory.
I'm guessing your systemd working directory is not where `public` folder is found

I have unfortunate news for you, though, as I am about to change how configuration works in goldfish for future releases. The instructions for the new release have already been [documented](https://github.com/Caiyeon/goldfish/wiki/Production-Deployment#3-deploy-release-version). The release will follow soon. There are specific [reasons](https://github.com/Caiyeon/goldfish/issues/59) for this change.

P.S. You don't need golang to deploy goldfish if you download the release versions :)

**Comment by klevermonicker** [comment]
Yea it hit me while I was out shopping about the working directory. I fixed it and goldfish comes up now without issue. 

As far as the config change, hey that's great news! Once 0.4 is out I'll update my systemd config...speaking of, Any interest in me providing you what I have for inclusion for people who want to run goldfish as a systemd service?

**Comment by Caiyeon** [comment]
A pre release is out if you are feeling adventurous. I'll remove the pre tag in a couple of days when no one raises issues with it. 

I would like the contribution, but I'm not sure where in the repo it would go. Perhaps in the wiki?

**Comment by Caiyeon** [comment]
Closing because the original issue has been resolved
