### ISSUE TITLE
Two errors about login instead of one 

### ISSUE THREAD

**Issue by dmitrykurmanov** [Caiyeon/goldfish#82]
Please check it 
![054f50cf85](https://user-images.githubusercontent.com/22315929/27382301-fc959c26-568e-11e7-8574-c12b98aaff94.jpg)

**Comment by Caiyeon** [comment]
This is expected behaviour. There are two async calls being made, one for csrf and one for listing users. To 'fix' this, they would have to be chained, and they shouldn't be
