### ISSUE TITLE
Failed to unwrap token

### ISSUE THREAD

**Issue by kevinjcash** [Caiyeon/goldfish#91]
```
$ sudo ./goldfish -config=/etc/goldfish/config.hcl -token=$VAULT_TOKEN
panic: Failed to unwrap provided token, revoke it if possible

goroutine 1 [running]:
main.main()
        /Users/tony/work/src/github.com/caiyeon/goldfish/server.go:77 +0x1dd
```
I've run all the steps listed here: https://github.com/Caiyeon/goldfish/wiki/Production-Deployment. I've tried storing the wrapped token in an env var and pasting it directly into the command. I'm seeing the same behavior on two separate machines. I'm running Goldfish release v0.4.0 and vault server v0.7.0.

**Comment by Caiyeon** [comment]
In your config file, does your vault address have a proper scheme? I.e. prefixed by http or https?
See https://github.com/Caiyeon/goldfish/issues/77

**Comment by kevinjcash** [comment]
Ah that was it! Sorry I should have looked harder at the issues.

**Comment by Caiyeon** [comment]
Not at all! I feel that the config parser should reject invalid addresses. 

An enforcement of http/https scheme will be added in v0.4.1 (which should actually arrive very very soon)
